-- APACHE Tables Migration
-- Creates tables for Apache Directional Spread Trading Bot
-- Run: psql $DATABASE_URL -f db/migrations/002_apache_tables.sql

-- ============================================================================
-- APACHE CONFIG TABLE
-- Stores configuration settings for the Apache bot
-- ============================================================================
CREATE TABLE IF NOT EXISTS apache_config (
    id SERIAL PRIMARY KEY,
    setting_name VARCHAR(50) NOT NULL UNIQUE,
    setting_value TEXT NOT NULL,
    description TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Insert default config
INSERT INTO apache_config (setting_name, setting_value, description) VALUES
    ('enabled', 'true', 'Whether Apache bot is enabled'),
    ('mode', 'paper', 'Trading mode: paper or live'),
    ('wall_filter_pct', '1.0', 'Only trade within X% of relevant GEX wall'),
    ('spread_width', '2', 'Width of spread in dollars'),
    ('contracts_per_trade', '10', 'Default number of contracts per trade'),
    ('max_daily_trades', '5', 'Maximum trades per day'),
    ('trailing_stop_pct', '0.3', 'Trailing stop percentage'),
    ('ticker', 'SPY', 'Ticker symbol to trade')
ON CONFLICT (setting_name) DO NOTHING;

-- ============================================================================
-- APACHE SIGNALS TABLE
-- Stores signals generated by Prophet for Apache
-- ============================================================================
CREATE TABLE IF NOT EXISTS apache_signals (
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    -- Signal details
    ticker VARCHAR(10) NOT NULL DEFAULT 'SPY',
    signal_direction VARCHAR(10) NOT NULL,  -- BULLISH, BEARISH, FLAT
    ml_confidence FLOAT,
    oracle_advice VARCHAR(20),  -- TRADE_FULL, TRADE_REDUCED, SKIP_TODAY

    -- GEX context
    gex_regime VARCHAR(10),  -- POSITIVE, NEGATIVE
    call_wall FLOAT,
    put_wall FLOAT,
    spot_price FLOAT,

    -- Spread recommendation
    spread_type VARCHAR(20),  -- BULL_CALL_SPREAD, BEAR_CALL_SPREAD
    reasoning TEXT,

    -- Status
    status VARCHAR(20) DEFAULT 'generated'  -- generated, executed, skipped, expired
);

CREATE INDEX IF NOT EXISTS idx_apache_signals_date ON apache_signals(created_at);
CREATE INDEX IF NOT EXISTS idx_apache_signals_direction ON apache_signals(signal_direction);
CREATE INDEX IF NOT EXISTS idx_apache_signals_status ON apache_signals(status);

-- ============================================================================
-- APACHE POSITIONS TABLE
-- Stores open and closed positions
-- ============================================================================
CREATE TABLE IF NOT EXISTS apache_positions (
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    -- Position identification
    position_id VARCHAR(50) NOT NULL UNIQUE,
    signal_id INTEGER REFERENCES apache_signals(id),

    -- Spread details
    spread_type VARCHAR(20) NOT NULL,  -- BULL_CALL_SPREAD, BEAR_CALL_SPREAD
    ticker VARCHAR(10) NOT NULL DEFAULT 'SPY',
    long_strike FLOAT NOT NULL,
    short_strike FLOAT NOT NULL,
    expiration DATE NOT NULL,

    -- Entry
    entry_price FLOAT NOT NULL,  -- Debit paid (or credit received if negative)
    entry_time TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    contracts INTEGER NOT NULL DEFAULT 1,
    max_profit FLOAT,
    max_loss FLOAT,

    -- Context at entry
    spot_at_entry FLOAT,
    gex_regime VARCHAR(10),
    oracle_confidence FLOAT,
    oracle_reasoning TEXT,

    -- Exit
    status VARCHAR(20) DEFAULT 'open',  -- open, closed, expired
    exit_price FLOAT,
    exit_time TIMESTAMP WITH TIME ZONE,
    exit_reason VARCHAR(50),  -- EOD_EXIT, TRAILING_STOP, PROFIT_TARGET, MANUAL
    realized_pnl FLOAT,

    -- Performance
    return_pct FLOAT,
    hold_time_minutes INTEGER
);

CREATE INDEX IF NOT EXISTS idx_apache_positions_status ON apache_positions(status);
CREATE INDEX IF NOT EXISTS idx_apache_positions_date ON apache_positions(created_at);
CREATE INDEX IF NOT EXISTS idx_apache_positions_spread ON apache_positions(spread_type);

-- ============================================================================
-- APACHE TRADES TABLE
-- Detailed execution log for each leg of a trade
-- ============================================================================
CREATE TABLE IF NOT EXISTS apache_trades (
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    -- Link to position
    position_id VARCHAR(50) REFERENCES apache_positions(position_id),

    -- Trade details
    trade_type VARCHAR(10) NOT NULL,  -- ENTRY, EXIT
    leg VARCHAR(10) NOT NULL,  -- LONG, SHORT
    action VARCHAR(10) NOT NULL,  -- BUY, SELL

    -- Option details
    ticker VARCHAR(10) NOT NULL,
    strike FLOAT NOT NULL,
    expiration DATE NOT NULL,
    option_type VARCHAR(10) NOT NULL,  -- CALL, PUT

    -- Execution
    quantity INTEGER NOT NULL,
    price FLOAT NOT NULL,
    fill_price FLOAT,
    commission FLOAT DEFAULT 0,

    -- Broker
    broker_order_id VARCHAR(100),
    broker_status VARCHAR(50),
    execution_time TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_apache_trades_position ON apache_trades(position_id);
CREATE INDEX IF NOT EXISTS idx_apache_trades_type ON apache_trades(trade_type);

-- ============================================================================
-- APACHE LOGS TABLE
-- Comprehensive logging for debugging and monitoring
-- ============================================================================
CREATE TABLE IF NOT EXISTS apache_logs (
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    log_level VARCHAR(10) NOT NULL,  -- DEBUG, INFO, WARNING, ERROR
    message TEXT NOT NULL,
    details JSONB,  -- Additional context

    -- Optional links
    position_id VARCHAR(50),
    signal_id INTEGER
);

CREATE INDEX IF NOT EXISTS idx_apache_logs_level ON apache_logs(log_level);
CREATE INDEX IF NOT EXISTS idx_apache_logs_date ON apache_logs(created_at);

-- ============================================================================
-- APACHE PERFORMANCE TABLE
-- Daily performance tracking
-- ============================================================================
CREATE TABLE IF NOT EXISTS apache_performance (
    id SERIAL PRIMARY KEY,
    trade_date DATE NOT NULL UNIQUE,

    -- Daily stats
    trades_executed INTEGER DEFAULT 0,
    trades_won INTEGER DEFAULT 0,
    trades_lost INTEGER DEFAULT 0,
    win_rate FLOAT,

    -- P&L
    gross_pnl FLOAT DEFAULT 0,
    commissions FLOAT DEFAULT 0,
    net_pnl FLOAT DEFAULT 0,

    -- Capital
    starting_capital FLOAT,
    ending_capital FLOAT,
    daily_return_pct FLOAT,

    -- Context
    avg_confidence FLOAT,
    bullish_trades INTEGER DEFAULT 0,
    bearish_trades INTEGER DEFAULT 0,

    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_apache_performance_date ON apache_performance(trade_date);

-- ============================================================================
-- VERIFICATION
-- ============================================================================
SELECT 'Apache tables created successfully' as status;
SELECT table_name FROM information_schema.tables
WHERE table_schema = 'public'
AND table_name LIKE 'apache_%'
ORDER BY table_name;
