-- WATCHTOWER Tables Migration
-- Creates tables for WATCHTOWER (0DTE Gamma Live) - Real-time gamma visualization and predictions
-- Run: psql $DATABASE_URL -f db/migrations/005_argus_tables.sql

-- ============================================================================
-- WATCHTOWER SNAPSHOTS TABLE
-- Stores gamma snapshots for each minute of trading
-- ============================================================================
CREATE TABLE IF NOT EXISTS watchtower_snapshots (
    id SERIAL PRIMARY KEY,
    symbol VARCHAR(10) NOT NULL DEFAULT 'SPY',
    expiration_date DATE NOT NULL,
    snapshot_time TIMESTAMP WITH TIME ZONE NOT NULL,

    -- Price context
    spot_price DECIMAL(10,2) NOT NULL,
    expected_move DECIMAL(10,2) NOT NULL,
    vix DECIMAL(5,2),

    -- Overall gamma regime
    total_net_gamma DECIMAL(20,4),
    gamma_regime VARCHAR(20),  -- POSITIVE, NEGATIVE, NEUTRAL
    previous_regime VARCHAR(20),  -- For flip detection
    regime_flipped BOOLEAN DEFAULT FALSE,

    -- Market status
    market_status VARCHAR(20) DEFAULT 'open',  -- pre_market, open, after_hours, closed

    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_watchtower_snapshots_time ON watchtower_snapshots(snapshot_time);
CREATE INDEX IF NOT EXISTS idx_watchtower_snapshots_expiration ON watchtower_snapshots(expiration_date);
CREATE INDEX IF NOT EXISTS idx_watchtower_snapshots_symbol ON watchtower_snapshots(symbol);

-- ============================================================================
-- WATCHTOWER STRIKES TABLE
-- Stores per-strike gamma data for each snapshot
-- ============================================================================
CREATE TABLE IF NOT EXISTS argus_strikes (
    id SERIAL PRIMARY KEY,
    snapshot_id INTEGER REFERENCES watchtower_snapshots(id) ON DELETE CASCADE,

    -- Strike data
    strike DECIMAL(10,2) NOT NULL,
    net_gamma DECIMAL(20,4) NOT NULL,
    call_gamma DECIMAL(20,4),
    put_gamma DECIMAL(20,4),

    -- Gamma flip tracking
    previous_net_gamma DECIMAL(20,4),
    gamma_flipped BOOLEAN DEFAULT FALSE,  -- Flipped from positive to negative or vice versa
    flip_direction VARCHAR(20),  -- POS_TO_NEG, NEG_TO_POS

    -- Probability and analytics
    probability DECIMAL(5,2),  -- Probability of price landing here

    -- Rate of change
    roc_1min DECIMAL(10,4),  -- 1-minute rate of change %
    roc_5min DECIMAL(10,4),  -- 5-minute rate of change %

    -- Volume and IV
    volume INTEGER,
    call_iv DECIMAL(5,2),
    put_iv DECIMAL(5,2),

    -- Classification
    is_magnet BOOLEAN DEFAULT FALSE,
    magnet_rank INTEGER,  -- 1, 2, or 3 for top magnets
    is_pin BOOLEAN DEFAULT FALSE,
    is_danger BOOLEAN DEFAULT FALSE,
    danger_type VARCHAR(20),  -- BUILDING, COLLAPSING, SPIKE

    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_argus_strikes_snapshot ON argus_strikes(snapshot_id);
CREATE INDEX IF NOT EXISTS idx_argus_strikes_strike ON argus_strikes(strike);
CREATE INDEX IF NOT EXISTS idx_argus_strikes_magnet ON argus_strikes(is_magnet);

-- ============================================================================
-- WATCHTOWER COMMENTARY TABLE
-- Stores Claude AI commentary generated every 5 minutes
-- ============================================================================
CREATE TABLE IF NOT EXISTS watchtower_commentary (
    id SERIAL PRIMARY KEY,
    snapshot_id INTEGER REFERENCES watchtower_snapshots(id),

    -- Commentary content
    commentary_text TEXT NOT NULL,

    -- Context at time of commentary
    spot_price DECIMAL(10,2),
    top_magnet DECIMAL(10,2),
    likely_pin DECIMAL(10,2),
    pin_probability DECIMAL(5,2),
    vix DECIMAL(5,2),

    -- Structured data
    danger_zones JSONB,
    gamma_flips JSONB,  -- Array of strikes that flipped
    magnet_changes JSONB,

    -- Bot context
    bot_positions JSONB,

    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_watchtower_commentary_time ON watchtower_commentary(created_at);
CREATE INDEX IF NOT EXISTS idx_watchtower_commentary_snapshot ON watchtower_commentary(snapshot_id);

-- ============================================================================
-- WATCHTOWER ALERTS TABLE
-- Stores all alerts generated by the system
-- ============================================================================
CREATE TABLE IF NOT EXISTS watchtower_alerts (
    id SERIAL PRIMARY KEY,

    -- Alert details
    alert_type VARCHAR(50) NOT NULL,  -- GAMMA_FLIP, REGIME_CHANGE, GAMMA_SPIKE, MAGNET_SHIFT, etc.
    strike DECIMAL(10,2),
    message TEXT NOT NULL,
    priority VARCHAR(10) NOT NULL,  -- HIGH, MEDIUM, LOW

    -- Context
    spot_price DECIMAL(10,2),
    old_value TEXT,  -- Previous state/value
    new_value TEXT,  -- New state/value

    -- Status
    triggered_at TIMESTAMP WITH TIME ZONE NOT NULL,
    acknowledged BOOLEAN DEFAULT FALSE,
    acknowledged_at TIMESTAMP WITH TIME ZONE,

    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_watchtower_alerts_time ON watchtower_alerts(triggered_at);
CREATE INDEX IF NOT EXISTS idx_watchtower_alerts_type ON watchtower_alerts(alert_type);
CREATE INDEX IF NOT EXISTS idx_watchtower_alerts_priority ON watchtower_alerts(priority);

-- ============================================================================
-- WATCHTOWER PREDICTIONS TABLE
-- Stores predictions for feedback loop and model training
-- ============================================================================
CREATE TABLE IF NOT EXISTS argus_predictions (
    id SERIAL PRIMARY KEY,

    -- Prediction context
    prediction_date DATE NOT NULL,
    expiration_date DATE NOT NULL,
    prediction_time TIMESTAMP WITH TIME ZONE NOT NULL,

    -- Pin prediction
    predicted_pin DECIMAL(10,2),
    pin_probability DECIMAL(5,2),

    -- Direction prediction
    predicted_direction VARCHAR(10),  -- UP, DOWN, FLAT
    direction_confidence DECIMAL(5,2),

    -- Structured predictions
    top_magnets JSONB,  -- Array of top 3 magnets with probabilities
    danger_zones JSONB,

    -- Pattern matching
    pattern_match VARCHAR(100),
    pattern_confidence DECIMAL(5,2),

    -- Model metadata
    model_version VARCHAR(20),

    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_argus_predictions_date ON argus_predictions(prediction_date);
CREATE INDEX IF NOT EXISTS idx_argus_predictions_expiration ON argus_predictions(expiration_date);

-- ============================================================================
-- WATCHTOWER OUTCOMES TABLE
-- Stores actual outcomes for feedback loop comparison
-- ============================================================================
CREATE TABLE IF NOT EXISTS argus_outcomes (
    id SERIAL PRIMARY KEY,
    prediction_id INTEGER REFERENCES argus_predictions(id),

    -- Outcome data
    outcome_date DATE NOT NULL,
    actual_close DECIMAL(10,2) NOT NULL,
    actual_high DECIMAL(10,2),
    actual_low DECIMAL(10,2),
    actual_pin_strike DECIMAL(10,2),

    -- Accuracy metrics
    pin_accuracy DECIMAL(5,2),  -- How close was pin prediction
    pin_error DECIMAL(10,2),  -- Dollar difference from predicted pin
    direction_correct BOOLEAN,
    magnet_touched BOOLEAN,  -- Did price touch any of the top 3 magnets

    -- Additional context
    notes TEXT,

    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_argus_outcomes_date ON argus_outcomes(outcome_date);
CREATE INDEX IF NOT EXISTS idx_argus_outcomes_prediction ON argus_outcomes(prediction_id);

-- ============================================================================
-- WATCHTOWER ACCURACY TABLE
-- Rolling accuracy metrics for dashboard
-- ============================================================================
CREATE TABLE IF NOT EXISTS argus_accuracy (
    id SERIAL PRIMARY KEY,
    metric_date DATE NOT NULL UNIQUE,

    -- Pin accuracy
    pin_accuracy_7d DECIMAL(5,2),
    pin_accuracy_30d DECIMAL(5,2),
    avg_pin_error_7d DECIMAL(10,2),
    avg_pin_error_30d DECIMAL(10,2),

    -- Direction accuracy
    direction_accuracy_7d DECIMAL(5,2),
    direction_accuracy_30d DECIMAL(5,2),

    -- Magnet accuracy
    magnet_hit_rate_7d DECIMAL(5,2),
    magnet_hit_rate_30d DECIMAL(5,2),

    -- Gamma flip accuracy (did flips predict moves)
    flip_accuracy_7d DECIMAL(5,2),
    flip_accuracy_30d DECIMAL(5,2),

    -- Totals
    total_predictions INTEGER,
    total_predictions_7d INTEGER,
    total_predictions_30d INTEGER,

    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_argus_accuracy_date ON argus_accuracy(metric_date);

-- ============================================================================
-- WATCHTOWER GAMMA FLIPS TABLE
-- Dedicated table to track all gamma flip events for analysis
-- ============================================================================
CREATE TABLE IF NOT EXISTS argus_gamma_flips (
    id SERIAL PRIMARY KEY,

    -- Flip context
    flip_time TIMESTAMP WITH TIME ZONE NOT NULL,
    expiration_date DATE NOT NULL,
    strike DECIMAL(10,2) NOT NULL,

    -- Flip details
    flip_direction VARCHAR(20) NOT NULL,  -- POS_TO_NEG, NEG_TO_POS
    gamma_before DECIMAL(20,4) NOT NULL,
    gamma_after DECIMAL(20,4) NOT NULL,

    -- Price context
    spot_at_flip DECIMAL(10,2),
    distance_from_spot DECIMAL(5,2),  -- Percentage

    -- Was this flip at a significant strike?
    was_magnet BOOLEAN DEFAULT FALSE,
    was_pin BOOLEAN DEFAULT FALSE,

    -- Outcome tracking (filled in later)
    price_30min_after DECIMAL(10,2),
    price_1hr_after DECIMAL(10,2),
    price_at_close DECIMAL(10,2),
    move_after_flip DECIMAL(5,2),  -- Percentage move
    flip_predicted_direction BOOLEAN,  -- Did price move in expected direction?

    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_argus_flips_time ON argus_gamma_flips(flip_time);
CREATE INDEX IF NOT EXISTS idx_argus_flips_strike ON argus_gamma_flips(strike);
CREATE INDEX IF NOT EXISTS idx_argus_flips_expiration ON argus_gamma_flips(expiration_date);

-- ============================================================================
-- VERIFICATION
-- ============================================================================
SELECT 'WATCHTOWER tables created successfully' as status;
SELECT table_name FROM information_schema.tables
WHERE table_schema = 'public'
AND table_name LIKE 'argus_%'
ORDER BY table_name;
