"""Per-bot Discord identity — the name + logo a bot's alerts post under.

SpreadWorks sends everything through ONE webhook (`DISCORD_WEBHOOK_URL`), and a
webhook URL is bound to one channel. But Discord lets each individual message
override the webhook's `username` and `avatar_url`, so bot alerts can arrive as
"SURGE" with SURGE's logo while the scheduled briefings still arrive as
SpreadWorks — same channel, no extra webhooks, no code duplication.

Avatars are generated by `spreadworks/scripts/gen_bot_avatars.py` from the same
`BOT_THEME` palette the bot's dashboard page uses, and are served as static
files off the backend's own frontend dist (see the SPA catch-all in
`backend/__init__.py`).
"""
from __future__ import annotations

import os

# Public origin that serves the committed frontend dist. Discord fetches the
# avatar server-side, so this MUST be publicly reachable — a private/internal
# Render hostname silently renders the default grey avatar instead.
DEFAULT_PUBLIC_BASE = "https://spreadworks-backend.onrender.com"

AVATAR_PATH = "/bots/{key}.png"


def public_base_url() -> str:
    return (os.getenv("PUBLIC_BASE_URL") or DEFAULT_PUBLIC_BASE).rstrip("/")


def avatar_url(bot: str) -> str | None:
    """Public URL of `bot`'s avatar, or None if no avatar was generated for it.

    Returning None (rather than a 404 URL) matters: Discord shows a broken
    grey default when `avatar_url` points at a missing file, whereas omitting
    the field falls back to the webhook's own icon — which is the SpreadWorks
    logo, a strictly better default for an unrecognised bot.
    """
    key = (bot or "").strip().lower()
    if not key or key not in AVATAR_KEYS:
        return None
    return f"{public_base_url()}{AVATAR_PATH.format(key=key)}"


def bot_identity(bot: str, display: str | None = None) -> dict[str, str]:
    """Webhook identity overrides for a bot alert: {} when nothing is known.

    `{}` is a valid return — `_send_webhook_sync(**identity)` then sends no
    override at all and the message keeps the webhook's SpreadWorks identity.
    """
    key = (bot or "").strip().lower()
    if not key:
        return {}
    identity: dict[str, str] = {"username": (display or key).strip().upper()}
    url = avatar_url(key)
    if url:
        identity["avatar_url"] = url
    return identity


# Keys with a generated PNG in frontend/dist/bots/. Kept as an explicit literal
# rather than an os.listdir() of the dist directory: the backend process and
# the dist folder are not guaranteed to be co-located (FRONTEND_DIST resolution
# has three fallbacks), and a wrong listdir would silently drop every avatar.
# Mirror this when adding a bot — run gen_bot_avatars.py, then add the key.
AVATAR_KEYS = frozenset({
    "afterburn", "afterglow", "backdraft", "delta", "drift", "ember",
    "embreach", "embreachq", "flashpoint", "flow", "meadow", "reversal",
    "ripple", "splash", "squall", "surge", "tempest", "thermal", "tide",
    "tsunami", "undertow", "updraft", "weekender", "wildfire",
})
