"""
155+ spread trading tips for daily rotation.
Covers all 14 required categories with 10+ tips each.
Format: plain list of strings.
"""

TIPS = [
    # === ENTRY TIMING (12) ===
    "Wait until 9:45-10:00 AM ET to enter spreads. The first 15 minutes are pure noise — let the opening range establish before committing capital.",
    "Mondays and Tuesdays are statistically the best days for directional debit spreads. The weekly trend often sets in the first two sessions.",
    "Wednesday through Thursday is prime Iron Condor territory. The weekly direction is usually established and theta decay accelerates into Friday.",
    "Enter credit spreads AFTER a big intraday move, not before. A 1%+ SPY move in the morning often exhausts the day's range — sell into the calm that follows.",
    "The 10:00 AM ET reversal is real. Many morning trends reverse when key economic data drops and opening algorithmic flow fades. Wait for it.",
    "The 'dead zone' from 11:00 AM to 1:00 PM ET is low-volatility, range-bound action. This is the ideal entry window for same-day Iron Condors.",
    "Don't enter any spread within 30 minutes of a major economic release (CPI, NFP, FOMC). Wait for the number, wait for the reaction, THEN position.",
    "If SPY gaps up or down at open, wait at least 30 minutes. Gaps often partially fill, and the real direction emerges after the first half hour.",
    "Friday afternoons are dangerous for new entries. Theta is maximal but gamma risk on 0DTE is extreme. Only enter if you're experienced with expiration-day dynamics.",
    "Sell premium (credit spreads) in the morning when IV is typically elevated. Buy premium (debit spreads) in the afternoon when IV often compresses.",
    "Use the futures overnight range as a guide. If ES traded in a tight range overnight, expect a range-bound day — good for Iron Condors.",
    "Enter spreads when the bid-ask spread is tightest. For SPY options, this is typically between 10:00 AM and 2:00 PM ET when liquidity is highest.",

    # === IV RANK & IMPLIED VOLATILITY (12) ===
    "Enter Iron Condors when IV Rank is above 50. High IV means you collect more premium and have more room for the trade to work.",
    "Buy debit spreads when IV Rank is below 20. Low IV means cheap options — your long leg costs less, improving risk-to-reward.",
    "IV Rank compares current IV to its 52-week range. IV Rank of 80 means current IV is in the top 20% — prime time for selling premium.",
    "IV Percentile tells you what percentage of days had lower IV. If IV Percentile is 90%, today's IV is higher than 90% of the past year — sell that premium.",
    "After earnings, IV gets crushed (IV crush). If you sold a credit spread before earnings, the IV drop alone can give you 40-60% of max profit overnight.",
    "VIX between 15-22 is the sweet spot for credit spreads. Premiums are fat enough to be worth the risk but the market isn't unstable.",
    "When VIX is below 13, premiums are razor-thin. Credit spreads barely pay. Switch to debit strategies or sit on your hands.",
    "When VIX spikes above 30, reduce position sizes by 50%. The market is scared, moves are violent, and even 'safe' spreads get blown up.",
    "IV skew matters: if put IV is much higher than call IV, the market is pricing in downside fear. Factor this into your strike selection.",
    "Track the VIX term structure. Contango (front < back) = calm markets, great for selling premium. Backwardation (front > back) = fear, be cautious.",
    "Implied volatility overstates realized moves about 85% of the time. This is the statistical edge that credit spread sellers exploit.",
    "After a vol spike, wait for VIX to start declining before selling spreads. Selling into a rising VIX is catching a falling knife.",

    # === STRIKE SELECTION (12) ===
    "Target the 16-delta strike for your short legs. This gives you approximately 84% theoretical probability of profit at entry.",
    "Use GEX levels to pick strikes: put walls are support, call walls are resistance. Place your short strikes outside these walls for maximum safety.",
    "Round number strikes ($550, $560, $570) act as magnets due to open interest clustering. Consider these levels when selecting your strikes.",
    "Check open interest at your chosen strikes before entering. High OI at your short strike means strong pinning effect — that's good for sellers.",
    "On SPY, use $1-wide spreads for precision. On SPX, $5-wide spreads are standard. Match strike width to the underlying's strike intervals.",
    "The expected move tells you where the market prices a 1-standard-deviation move. Selling strikes outside this range gives you approximately 68% odds.",
    "Always check the bid-ask spread at your chosen strikes. Wide bid-ask means expensive entry AND exit — it silently destroys your edge.",
    "Volume and open interest at a strike indicate where institutional money is positioned. High OI at a level means potential support or resistance.",
    "Place short strikes where you see natural support/resistance on the chart. Let technical analysis confirm your options thesis.",
    "The GEX flip point divides momentum from mean-reversion territory. If price is above the flip, put spreads are safer. Below the flip, call spreads have the edge.",
    "For weekly spreads, select strikes 0.5 to 1.0 standard deviations away. For monthly, go 1.0 to 1.5 standard deviations for extra cushion.",
    "Avoid strikes directly at recent highs or lows. If SPY just bounced off $560, putting your short put right at $560 is inviting trouble.",

    # === DTE MANAGEMENT (12) ===
    "0DTE spreads maximize theta but gamma is a loaded spring. Only trade these if you can monitor positions all day and exit quickly.",
    "1-3 DTE spreads offer the best theta-to-gamma ratio for experienced traders. Enough time to be right, short enough for rapid time decay.",
    "5-7 DTE (weekly) spreads are the sweet spot for most traders. Good theta decay, manageable gamma, and enough time to be wrong and recover.",
    "21-45 DTE spreads are best for calendar and diagonal strategies. This range gives you the highest vega exposure and time for your thesis to play out.",
    "Don't hold short-dated spreads over the weekend. Friday's theta benefit doesn't compensate for the gap risk of Monday's open.",
    "The last 21 days is when theta decay accelerates the most. This is why weeklies are the spread trader's bread and butter.",
    "If your 0DTE Iron Condor isn't at 50% profit by 2:00 PM ET, strongly consider closing it. The last 2 hours carry disproportionate gamma risk.",
    "For debit spreads, add 2-3x the expected time to your thesis. If you think the move takes 3 days, buy 7-10 DTE to account for timing uncertainty.",
    "Selling 45+ DTE options collects premium but ties up capital for weeks. Unless you're running a wheel strategy, shorter DTE is more capital efficient.",
    "0DTE is not beginner-friendly. Start with 5-7 DTE spreads, master those, then graduate to shorter durations as your skill improves.",
    "Match DTE to the catalyst. If CPI is in 3 days, a 5 DTE spread captures the event. A 0DTE spread today misses it entirely.",
    "As expiration approaches, your spread's P&L becomes increasingly binary. Either it expires worthless (full profit) or gets breached (max loss). Manage early.",

    # === PROFIT TAKING (11) ===
    "Close credit spreads at 50% of max profit. You've captured the easy half — the remaining 50% carries disproportionate risk for diminishing reward.",
    "For Iron Condors, take profits at 25-50% if you have more than 5 days to expiration. Redeploy that capital into a fresh trade.",
    "Don't get greedy waiting for the last $0.05 of premium. Close your spread when it's profitable and free up your capital and mental bandwidth.",
    "If your credit spread reaches 75% profit with more than 2 days to expiration, close it. That remaining 25% isn't worth the overnight risk.",
    "Trail your stop on debit spreads. If your debit spread doubles in value, move your stop to breakeven. Let winners run but protect the gain.",
    "Exit debit spreads at 50-100% profit. Unlike credit spreads, theta works against you on debit positions — take gains when you have them.",
    "A winning trade that reverses into a loser is the most psychologically damaging outcome. Set profit targets and honor them.",
    "After a VIX drop of 3+ points, consider closing credit spreads early. The volatility crush alone may have given you most of your profit.",
    "Partial profit-taking works: close half your contracts at 50% profit and let the rest run to 75%. This balances locking in gains with upside potential.",
    "Time-based exits work: if your spread hasn't reached 50% profit by the halfway point of its DTE, consider closing for whatever profit or small loss exists.",
    "Never let a winning trade become a big loser. If your credit spread was up 60% and reversed, close it — don't wait for it to hit max loss.",

    # === STOP LOSS & RISK MANAGEMENT (12) ===
    "Never risk more than 2-5% of your account on a single spread trade. One bad trade should never blow up your week or month.",
    "Define your max loss BEFORE entering the trade. With spreads, your max loss is (strike width - credit) × contracts × 100. Know the number.",
    "If you lose 2 trades in a row, take a 30-minute break. Emotional trading after losses leads to revenge trades and even bigger losses.",
    "Set a daily loss limit at 3-5% of your account. If you hit it, stop trading for the day. No single day should derail your month.",
    "Position size based on max loss, not premium collected. A spread collecting $1.00 with $4.00 max loss is a $400 risk trade per contract.",
    "The biggest risk in 0DTE trading is gamma explosion. As expiration approaches, small price moves cause huge P&L swings. Size down on 0DTE.",
    "Have three exit rules for every spread: profit target (50-75%), time stop (close by a certain time), and loss limit (2x credit collected).",
    "When in doubt, reduce size. It's better to make a small profit on a winning trade than take a big loss on an oversized position.",
    "A 10% drawdown needs 11% to recover. A 50% drawdown needs 100%. This is why protecting capital matters more than growing it.",
    "Correlation kills diversification: don't sell put spreads on SPY, QQQ, and IWM simultaneously. They all drop together — that's concentration, not diversification.",
    "Keep a trading journal. Log every spread: entry reason, strikes, DTE, Greeks, outcome, and lessons learned. Data beats emotion every time.",
    "The spread itself IS risk management — it caps your loss. But you still need to manage how many spreads you run simultaneously.",

    # === EARNINGS AVOIDANCE (10) ===
    "Never hold an Iron Condor through a major earnings report (AAPL, MSFT, NVDA, AMZN). Post-earnings moves routinely blow past expected ranges.",
    "Check the earnings calendar every Sunday night. Know which companies report each day so you're never surprised by a gap-up or gap-down.",
    "Earnings IV crush is predictable but the direction isn't. If you must trade earnings, use strategies that profit from IV crush regardless of direction.",
    "Close all single-stock spreads at least one day before earnings. Even if you're right on direction, a massive gap can breach your strikes.",
    "During earnings season (Jan, Apr, Jul, Oct), individual stock moves can drag entire sectors. Watch sector ETF correlations with your index spreads.",
    "If a mega-cap (AAPL, MSFT, NVDA) reports after the bell, expect elevated index volatility the next morning. Size down on index spreads that week.",
    "Earnings straddle IV is the market's best guess at the post-earnings move. If the straddle implies 5%, placing short strikes 3% away is gambling.",
    "After a company reports, its implied volatility drops 20-60% overnight. This is IV crush — it's predictable and exploitable with the right spread.",
    "Calendar spreads around earnings can exploit the IV skew between pre-earnings and post-earnings expirations. Advanced strategy, but powerful.",
    "Bank earnings kick off each earnings season. Their results set the tone for the entire market. Pay attention to JPM, GS, and MS reports.",

    # === GEX & GAMMA EXPOSURE AWARENESS (12) ===
    "Positive GEX means dealers are long gamma — they buy dips and sell rips. This creates mean-reversion. Iron Condors thrive in positive GEX.",
    "Negative GEX means dealers are short gamma — they sell dips and buy rips. This amplifies moves. Debit spreads and directional plays work best.",
    "The GEX flip point is where dealer behavior switches from stabilizing to destabilizing. Know where it is — it's the most important level of the day.",
    "When price is above the GEX flip point, put credit spreads have an extra edge. Dealers are actively pushing price up if it dips.",
    "When price is below the GEX flip point, call credit spreads are safer. Dealers are actively capping rallies.",
    "Call walls represent resistance where dealers sell into rallies. Put walls represent support where dealers buy dips. Use both for strike selection.",
    "GEX magnets are price levels that attract and hold price. The strongest magnet makes an excellent center strike for Iron Condors and calendars.",
    "On days with very high positive GEX (top 20%), sell tighter Iron Condors. The mean-reversion is strong enough that you can collect more premium safely.",
    "On days with extreme negative GEX (bottom 20%), avoid Iron Condors entirely. Breakouts will follow through and destroy both wings.",
    "GEX changes throughout the day as new options are traded. Check levels at open, midday, and before entering afternoon trades.",
    "The standard deviation bounds from GEX analysis show where 68% of the day's price action is expected. Sell credit spread strikes outside these bounds.",
    "GEX expiration-day dynamics are different from regular days. On OpEx Fridays, gamma exposure is massive and price often pins to the highest OI strike.",

    # === DOUBLE DIAGONAL SPECIFICS (10) ===
    "A double diagonal combines a bull call diagonal with a bear put diagonal. You sell near-term OTM options and buy longer-dated, further OTM options.",
    "Double diagonals profit from time decay on the short legs while maintaining protection with the long legs. It's like an Iron Condor with a time twist.",
    "The ideal double diagonal has 5-7 DTE on the short legs and 21-30 DTE on the long legs. This maximizes the theta differential.",
    "Double diagonals benefit when the front-month IV is higher than the back-month IV. This term structure skew adds to your edge.",
    "When rolling double diagonal short legs, always roll for a net credit. If you can't get a credit on the roll, consider closing the entire position.",
    "Manage double diagonals by rolling the short legs weekly while keeping the long legs as a protective anchor. Each roll reduces your cost basis.",
    "Double diagonals have positive theta AND positive vega on the long legs. If IV rises, your long legs increase in value — a built-in hedge.",
    "Select short strikes on your double diagonal at 20-25 delta. This gives enough premium to collect while keeping a comfortable distance from spot price.",
    "If one side of your double diagonal is threatened, roll that short leg out and away. Don't wait for max loss — proactive management is key.",
    "Double diagonals are more capital efficient than Iron Condors because the long legs are further out in time, not just further in strike.",

    # === DOUBLE CALENDAR SPECIFICS (10) ===
    "A double calendar spread places a put calendar and a call calendar at different strikes, creating a wide profit zone centered around the current price.",
    "Double calendars profit from the front-month option decaying faster than the back-month option. The wider the time gap, the bigger the theta differential.",
    "Center your double calendar wings around the expected pin price. If GEX shows a strong magnet at $575, place your calendars around that level.",
    "The ideal double calendar uses 7 DTE for the short legs and 30-45 DTE for the long legs. This maximizes the 'time gap' for premium harvesting.",
    "Double calendars are vega positive — they benefit when implied volatility increases. Great for positioning before expected volatility events.",
    "Avoid double calendars that straddle an earnings date. If earnings falls between your two expirations, the IV skew can work violently against you.",
    "Monitor the IV differential between your front and back months. If front-month IV drops below back-month IV, your calendar's edge is shrinking.",
    "Double calendars at ATM strikes have the highest theta differential. Place your put calendar slightly below current price and call calendar slightly above.",
    "Close double calendars when the front legs expire or when you've captured 25-40% of the max theoretical profit. Don't hold for the last few pennies.",
    "If price moves sharply away from your double calendar center, cut the losing side early. The remaining side can still be profitable.",

    # === IRON CONDOR ADJUSTMENTS (12) ===
    "If price approaches your short put strike, roll the untested call side closer to collect additional credit. This reduces your overall risk.",
    "When one wing of your IC is threatened, you have three choices: roll that wing out/away, close that wing and keep the safe side, or close the entire IC.",
    "Rolling an IC wing 'out and away' means moving to the next expiration at a wider strike. Roll for a net credit if possible.",
    "If your IC reaches 50% max loss, close it. Don't hope for a reversal. The math of recovery doesn't favor holding a deeply underwater IC.",
    "Inverted Iron Condors (closing the tested side and rolling past center) is an advanced technique. Only attempt it if you understand the risk transformation.",
    "Convert a losing IC to a single credit spread: close the losing side, keep the winning side. You've reduced complexity and are now managing one spread.",
    "If both sides of your IC are tested (whipsaw day), close everything. The market is too volatile for range-bound strategies today.",
    "Pre-plan your adjustment triggers: 'If short strike is breached by $X, I do Y.' Having the plan ready prevents panic decisions.",
    "Adjustment timing matters: adjusting too early locks in a loss that might have recovered. Too late and the loss is too big. Use 50% of premium as a trigger.",
    "After adjusting an IC, recalculate your max profit, max loss, and breakevens. The adjusted position is a NEW trade — treat it that way.",
    "If VIX spikes while your IC is on, don't panic. Higher VIX increases your short options' value temporarily, but time decay still works for you if strikes hold.",
    "Consider 'Iron Butterfly' adjustment: close the wings and bring the short strikes to ATM for a last-resort aggressive credit collection.",

    # === MARKET REGIME AWARENESS (11) ===
    "In trending markets, sell credit spreads WITH the trend. If SPY is trending up, sell put credit spreads. Trend + theta = double edge.",
    "In range-bound markets, Iron Condors are king. Identify the range boundaries from GEX levels and sell just outside them.",
    "When the market regime shifts (trending → range-bound or vice versa), your strategy must shift too. The fastest way to lose money is using the wrong strategy for the regime.",
    "Positive GEX + Low VIX = Sell premium aggressively. This is the ideal Iron Condor regime — dealers stabilize and time decay works.",
    "Negative GEX + High VIX = Maximum caution. Either sit out, use debit spreads only, or reduce credit spread size by 50%+.",
    "The first week of a new regime is the most dangerous. When VIX transitions from low to high, the initial spike often overshoots. Don't fight it.",
    "Track the 20-day and 50-day VIX moving averages. VIX below its 20-day MA = calm environment. VIX above both MAs = elevated risk.",
    "Sector rotation tells you where institutional money is flowing. If defensive sectors lead (utilities, healthcare), the market may be shifting to risk-off.",
    "Holiday-shortened weeks tend to be lower volume and range-bound. These are ideal Iron Condor weeks, but close all positions before the holiday.",
    "FOMC weeks have a predictable pattern: sideways before the meeting, then a sharp move after. Consider calendars that exploit this pattern.",
    "Triple witching days (quarterly OpEx) have massive gamma exposure. Use extra caution with Iron Condors and consider widening your strikes.",

    # === POSITION SIZING (11) ===
    "Risk no more than 1-3% of your total account per spread trade. This means if your account is $25,000, max risk per trade is $250-$750.",
    "Calculate position size from max loss, not premium. A $5-wide spread at $1.50 credit has $3.50 max loss per contract. Size from the $350, not the $150.",
    "Scale position sizes with conviction. A+ setups deserve full size. B setups get half size. C setups get skipped entirely.",
    "After a losing streak (3+ consecutive losses), cut your position size in half. Rebuild size gradually as wins return.",
    "Never increase position size after a winning streak. This is when overconfidence leads to oversizing, and the inevitable loss hits harder.",
    "Account for commissions in your sizing. On a $0.50 credit spread, commissions can eat 5-10% of your profit. Factor it in.",
    "Diversify position sizes across time: don't put all your capital in one expiration date. Spread risk across multiple expirations.",
    "For 0DTE positions, use half your normal size. Gamma risk doubles near expiration — your sizing should adjust accordingly.",
    "If your max loss on all open positions exceeds 15% of your account, you're overexposed. Close or reduce until total risk is manageable.",
    "Kelly Criterion suggests optimal bet sizing based on win rate and payoff ratio. For a 70% WR with 1:2 payoff, Kelly says risk ~25% — but use half-Kelly (12.5%) for safety.",
    "Position size should shrink as VIX rises. If VIX is 25+ (vs normal 15), reduce sizes proportionally. The market's range has expanded — your risk per contract is larger.",

    # === ROLLING STRATEGIES (11) ===
    "Rolling a spread means closing the current position and opening a new one at a different strike or expiration. It's not free — it costs slippage and commissions.",
    "Roll credit spreads OUT (further expiration) for more time and additional credit. Only roll if you still believe the original directional thesis.",
    "Roll credit spreads AWAY (further OTM) to create more distance from spot price. This reduces premium collected but increases probability of profit.",
    "Never roll for a debit. If you can't get a net credit when rolling a credit spread, it's better to close and find a new setup.",
    "Rolling Iron Condor wings: roll the tested (threatened) side out and away first. Then consider rolling the untested side closer for additional credit.",
    "The 21 DTE rule for rolling: if your spread is at a loss with 21+ DTE remaining, consider rolling. Under 21 DTE, the theta decay may save you — be patient.",
    "Don't roll the same losing trade more than twice. After two rolls, the position has changed character completely. Cut your losses and move on.",
    "Rolling calendar spread short legs weekly is the primary income mechanism. Each roll should collect premium that reduces your total cost basis.",
    "Roll diagonal spread short legs on Friday for the following week. This captures the weekend theta premium on the new short leg.",
    "If rolling your spread requires widening the strikes significantly, you're essentially entering a new trade. Treat it with the same analysis as a new entry.",
    "Track your rolling P&L separately. Sometimes a series of rolls disguises a losing trade that should have been closed. Honest accounting prevents this.",

    # === ADDITIONAL WISDOM (10) ===
    "Spreads are defined-risk by nature. This is their superpower — you always know your worst case before you enter. Use this advantage.",
    "The bid-ask spread on your options is a hidden cost. On SPY, it's usually $0.01-0.03. On illiquid stocks, it can be $0.10-0.30. Stick to liquid underlyings.",
    "Paper trade for at least 2 weeks before going live with any new spread strategy. Build confidence in execution before risking real capital.",
    "The best trade you'll ever make is the one you DON'T take when conditions are wrong. Sitting out is a strategy. Cash is a position.",
    "Keep it simple. One strategy, one underlying, mastered over months. Complexity is the enemy of execution under pressure.",
    "The most common spread trading mistake: sizing too big, then panicking when the trade goes against you. Size smaller. Sleep better. Trade longer.",
    "Use the 'would I enter this trade at this price right now?' test. If the answer is no, then you should probably close the position.",
    "Market makers profit from the bid-ask spread, not from direction. When you use limit orders at the mid-price, you deny them half their edge.",
    "Trading is a skill, not a talent. Skills are developed through deliberate practice — repetition with feedback. Journal, review, improve, repeat.",
    "The market pays you for taking risk and being patient. Spreads let you define exactly how much risk you take. Discipline determines how patient you are.",
]
