"""
VIX Volatility Hedge Manager - Signal Generation for Portfolio Protection
==========================================================================

This module generates SIGNALS for VIX-based hedging strategies.
It does NOT auto-execute trades because VIX hedging requires human judgment.

KEY PRINCIPLES:
1. VIX options track VIX FUTURES, not VIX spot
2. VIX futures are in contango ~80% of the time (constant theta bleed)
3. Correlation between SPY/SPX and VIX is non-linear and asymmetric
4. When you need protection most (crashes), spreads blow out 500%+

STRATEGIES MONITORED:
1. IV Percentile vs Realized Vol spread
2. VIX Term Structure (contango/backwardation)
3. VVIX (volatility of VIX) for timing
4. Cross-asset correlation regime

OUTPUT: Signal generator, NOT autonomous executor
"""

from dataclasses import dataclass, field
from datetime import datetime, timedelta
from typing import Dict, List, Optional, Tuple
from enum import Enum
from zoneinfo import ZoneInfo
from database_adapter import get_connection
import numpy as np
import pandas as pd

CENTRAL_TZ = ZoneInfo("America/Chicago")

# UNIFIED Data Provider (Tradier primary, Polygon fallback)
try:
    from unified_data_provider import get_data_provider, get_vix
    UNIFIED_DATA_AVAILABLE = True
except ImportError:
    UNIFIED_DATA_AVAILABLE = False

# Legacy Polygon fallback
try:
    from polygon_data_fetcher import polygon_fetcher
    POLYGON_AVAILABLE = True
except ImportError:
    POLYGON_AVAILABLE = False


class HedgeSignalType(Enum):
    """Types of hedge signals"""
    BUY_VIX_CALLS = "buy_vix_calls"           # Buy protection
    BUY_VIX_CALL_SPREAD = "buy_vix_call_spread"  # Cheaper protection
    SELL_VIX_PUTS = "sell_vix_puts"           # Sell vol (dangerous)
    REDUCE_HEDGE = "reduce_hedge"             # Take off protection
    NO_ACTION = "no_action"                   # Stay flat
    ROLL_HEDGE = "roll_hedge"                 # Roll existing position


class VolRegime(Enum):
    """Volatility regime classification"""
    VERY_LOW = "very_low"       # VIX < 12 - complacent, protection cheap
    LOW = "low"                 # VIX 12-15 - normal low
    NORMAL = "normal"           # VIX 15-20 - typical conditions
    ELEVATED = "elevated"       # VIX 20-25 - heightened concern
    HIGH = "high"               # VIX 25-35 - fear mode
    EXTREME = "extreme"         # VIX > 35 - panic


@dataclass
class HedgeSignal:
    """A hedge signal generated by the manager"""
    timestamp: datetime
    signal_type: HedgeSignalType
    confidence: float  # 0-100
    vol_regime: VolRegime
    reasoning: str
    recommended_action: str
    risk_warning: str
    metrics: Dict = field(default_factory=dict)


class VIXHedgeManager:
    """
    VIX-based volatility hedge signal generator for SPY/SPX portfolios.

    CRITICAL: This generates SIGNALS only, not trades.
    Human review required before execution.
    """

    def __init__(self):
        """Initialize the VIX hedge manager"""
        self.lookback_days = 252  # 1 year for IV percentile
        self.rv_window = 20  # 20-day realized vol
        self._ensure_tables()

        # VIX thresholds
        self.vol_thresholds = {
            'very_low': 12,
            'low': 15,
            'normal': 20,
            'elevated': 25,
            'high': 35
        }

        # Signal generation parameters
        self.iv_rv_spread_threshold = 5.0  # Points difference for signal
        self.term_structure_threshold = 3.0  # Contango/backwardation threshold

        print("✅ VIX Hedge Manager initialized (SIGNAL GENERATOR ONLY)")

    def _ensure_tables(self):
        """Create database tables for hedge signal tracking"""
        conn = get_connection()
        c = conn.cursor()

        c.execute("""
            CREATE TABLE IF NOT EXISTS vix_hedge_signals (
                id SERIAL PRIMARY KEY,
                signal_date DATE,
                signal_time TIME,
                signal_type VARCHAR(50),
                confidence DECIMAL(5,2),
                vol_regime VARCHAR(20),
                vix_spot DECIMAL(6,2),
                vix_futures_m1 DECIMAL(6,2),
                vix_futures_m2 DECIMAL(6,2),
                term_structure_pct DECIMAL(6,2),
                iv_percentile DECIMAL(5,2),
                realized_vol_20d DECIMAL(6,2),
                iv_rv_spread DECIMAL(6,2),
                spy_spot DECIMAL(8,2),
                reasoning TEXT,
                recommended_action TEXT,
                risk_warning TEXT,
                was_acted_on BOOLEAN DEFAULT FALSE,
                outcome_pnl DECIMAL(12,2),
                created_at TIMESTAMP DEFAULT NOW()
            )
        """)

        c.execute("""
            CREATE TABLE IF NOT EXISTS vix_hedge_positions (
                id SERIAL PRIMARY KEY,
                entry_date DATE,
                entry_time TIME,
                position_type VARCHAR(50),
                vix_strike DECIMAL(6,2),
                expiration_date DATE,
                contracts INTEGER,
                entry_price DECIMAL(8,4),
                current_price DECIMAL(8,4),
                unrealized_pnl DECIMAL(12,2),
                status VARCHAR(20) DEFAULT 'OPEN',
                hedge_target VARCHAR(50),
                created_at TIMESTAMP DEFAULT NOW()
            )
        """)

        conn.commit()
        conn.close()

    def get_vix_data(self) -> Dict:
        """
        Get comprehensive VIX data for analysis.

        Returns:
            Dict with VIX spot, futures, term structure, etc.
        """
        try:
            # VIX spot - Try unified provider (Tradier) first
            vix_spot = None
            if UNIFIED_DATA_AVAILABLE:
                vix_spot = get_vix()

            # Fallback to Polygon
            if (not vix_spot or vix_spot <= 0) and POLYGON_AVAILABLE:
                vix_spot = polygon_fetcher.get_current_price('^VIX')

            if not vix_spot or vix_spot <= 0:
                vix_spot = 18.0  # Reasonable default

            # For VIX futures, we'd need futures data
            # Using VIX9D (9-day) and VIX3M (3-month) as proxies if available
            # For now, estimate from spot
            vix_m1 = vix_spot * 1.05  # Typical contango ~5%
            vix_m2 = vix_spot * 1.08  # ~8% for M2

            # Calculate term structure
            if vix_spot > 0:
                term_structure_m1 = ((vix_m1 - vix_spot) / vix_spot) * 100
                term_structure_m2 = ((vix_m2 - vix_spot) / vix_spot) * 100
            else:
                term_structure_m1 = 5.0
                term_structure_m2 = 8.0

            # Determine if contango or backwardation
            structure_type = "contango" if term_structure_m1 > 0 else "backwardation"

            return {
                'vix_spot': vix_spot,
                'vix_m1': vix_m1,
                'vix_m2': vix_m2,
                'term_structure_m1_pct': term_structure_m1,
                'term_structure_m2_pct': term_structure_m2,
                'structure_type': structure_type,
                'timestamp': datetime.now(CENTRAL_TZ).isoformat()
            }

        except Exception as e:
            print(f"Error getting VIX data: {e}")
            return {
                'vix_spot': 18.0,
                'error': str(e)
            }

    def calculate_iv_percentile(self, vix_current: float) -> float:
        """
        Calculate current VIX percentile over lookback period.

        Uses historical VIX data to determine where current VIX sits.
        """
        try:
            # Get historical VIX data
            data = polygon_fetcher.get_price_history(
                '^VIX',
                days=self.lookback_days,
                timeframe='day'
            )

            if data is None or len(data) < 50:
                # Fallback: use typical VIX distribution
                # Historical mean ~17, std ~6
                from scipy import stats
                percentile = stats.percentileofscore([12, 14, 16, 18, 20, 22, 25, 30, 35], vix_current)
                return percentile

            # Calculate percentile
            vix_history = data['Close'].values
            percentile = (np.sum(vix_history <= vix_current) / len(vix_history)) * 100

            return percentile

        except Exception as e:
            print(f"Error calculating IV percentile: {e}")
            # Estimate based on typical VIX range
            if vix_current < 12:
                return 5
            elif vix_current < 15:
                return 20
            elif vix_current < 18:
                return 40
            elif vix_current < 22:
                return 60
            elif vix_current < 28:
                return 80
            else:
                return 95

    def calculate_realized_vol(self, symbol: str = 'SPY') -> float:
        """
        Calculate 20-day realized volatility for SPY.

        Returns annualized volatility percentage.
        """
        try:
            data = polygon_fetcher.get_price_history(
                symbol,
                days=30,
                timeframe='day'
            )

            if data is None or len(data) < self.rv_window:
                return 18.0  # Default estimate

            # Calculate log returns
            returns = np.log(data['Close'] / data['Close'].shift(1)).dropna()

            # Use last 20 days
            recent_returns = returns.tail(self.rv_window)

            # Annualized volatility
            rv = recent_returns.std() * np.sqrt(252) * 100

            return rv

        except Exception as e:
            print(f"Error calculating realized vol: {e}")
            return 18.0

    def get_vol_regime(self, vix: float) -> VolRegime:
        """Classify current volatility regime"""
        if vix < self.vol_thresholds['very_low']:
            return VolRegime.VERY_LOW
        elif vix < self.vol_thresholds['low']:
            return VolRegime.LOW
        elif vix < self.vol_thresholds['normal']:
            return VolRegime.NORMAL
        elif vix < self.vol_thresholds['elevated']:
            return VolRegime.ELEVATED
        elif vix < self.vol_thresholds['high']:
            return VolRegime.HIGH
        else:
            return VolRegime.EXTREME

    def generate_hedge_signal(
        self,
        portfolio_delta: float = 0,
        portfolio_value: float = 100000
    ) -> HedgeSignal:
        """
        Generate a hedge signal based on current market conditions.

        Args:
            portfolio_delta: Current portfolio delta exposure
            portfolio_value: Total portfolio value

        Returns:
            HedgeSignal with recommendation
        """
        now = datetime.now(CENTRAL_TZ)

        # Gather data
        vix_data = self.get_vix_data()
        vix_spot = vix_data.get('vix_spot', 18.0)

        iv_percentile = self.calculate_iv_percentile(vix_spot)
        realized_vol = self.calculate_realized_vol('SPY')

        vol_regime = self.get_vol_regime(vix_spot)
        term_structure = vix_data.get('term_structure_m1_pct', 5.0)

        # Calculate IV - RV spread
        iv_rv_spread = vix_spot - realized_vol

        # Get SPY price for context
        try:
            spy_spot = polygon_fetcher.get_current_price('SPY')
        except:
            spy_spot = 500.0

        # Decision logic
        signal_type = HedgeSignalType.NO_ACTION
        confidence = 50.0
        reasoning = ""
        recommended_action = ""
        risk_warning = ""

        # SCENARIO 1: Very low VIX + IV cheap relative to RV
        # This is when protection is cheap - good time to buy
        if vol_regime in [VolRegime.VERY_LOW, VolRegime.LOW] and iv_rv_spread < 2:
            signal_type = HedgeSignalType.BUY_VIX_CALL_SPREAD
            confidence = 75.0
            reasoning = (
                f"VIX at {vix_spot:.1f} ({iv_percentile:.0f}th percentile) - PROTECTION IS CHEAP. "
                f"IV-RV spread only {iv_rv_spread:.1f}pts. "
                f"Term structure in {vix_data.get('structure_type', 'contango')} ({term_structure:.1f}%). "
                f"This is an opportune time to add portfolio protection at low cost."
            )
            recommended_action = (
                f"Consider buying VIX call spread: "
                f"Buy VIX {int(vix_spot + 5)} calls, Sell VIX {int(vix_spot + 15)} calls. "
                f"Target 1-2 months expiration. "
                f"Cost should be ~0.5-1.5% of portfolio value."
            )
            risk_warning = (
                "WARNING: VIX options decay via contango roll. "
                "Protection cost ~3-5% per month if held through roll. "
                "Set maximum holding period."
            )

        # SCENARIO 2: Elevated VIX + IV expensive relative to RV
        # Reduce or avoid adding protection
        elif vol_regime in [VolRegime.ELEVATED, VolRegime.HIGH] and iv_rv_spread > 8:
            signal_type = HedgeSignalType.REDUCE_HEDGE
            confidence = 65.0
            reasoning = (
                f"VIX at {vix_spot:.1f} ({iv_percentile:.0f}th percentile) - PROTECTION IS EXPENSIVE. "
                f"IV-RV spread {iv_rv_spread:.1f}pts (RV only {realized_vol:.1f}%). "
                f"Protection costs are elevated - poor risk/reward for new hedges."
            )
            recommended_action = (
                f"Do NOT add new VIX protection at these levels. "
                f"If holding existing hedges, consider taking profit if >30% gain. "
                f"Wait for VIX pullback below {self.vol_thresholds['normal']} before adding."
            )
            risk_warning = (
                "WARNING: High VIX often mean-reverts. "
                "Buying protection here risks paying peak prices. "
                "However, if a major event is imminent, protection may still be warranted."
            )

        # SCENARIO 3: Extreme VIX (panic)
        # DO NOT buy protection here
        elif vol_regime == VolRegime.EXTREME:
            signal_type = HedgeSignalType.NO_ACTION
            confidence = 80.0
            reasoning = (
                f"VIX at {vix_spot:.1f} (EXTREME) - DO NOT ADD PROTECTION HERE. "
                f"Panic conditions - spreads are widest, prices are highest. "
                f"If you don't have protection now, it's too late for this move."
            )
            recommended_action = (
                "DO NOT buy VIX protection during panic. "
                "Instead, consider: (1) Reduce equity exposure, (2) Wait for VIX to normalize, "
                "(3) Use SPY/SPX put spreads which may have tighter markets."
            )
            risk_warning = (
                "CRITICAL: VIX options during panic have 500%+ wider spreads. "
                "Any protection bought here will immediately lose 20-30% to bid/ask. "
                "This is NOT the time to buy insurance."
            )

        # SCENARIO 4: Backwardation (VIX futures below spot)
        # Unusual - usually during stress or right after spike
        elif term_structure < -2:
            signal_type = HedgeSignalType.ROLL_HEDGE
            confidence = 60.0
            reasoning = (
                f"VIX term structure in BACKWARDATION ({term_structure:.1f}%). "
                f"This is unusual and typically occurs during/after stress events. "
                f"Backwardation means futures decay POSITIVELY - hedges actually gain from roll."
            )
            recommended_action = (
                "If holding VIX protection, consider EXTENDING duration. "
                "Roll from near-month to further-out expiration. "
                "Backwardation is favorable for VIX longs."
            )
            risk_warning = (
                "Backwardation usually resolves within days to weeks. "
                "VIX spike may have already occurred - late entry carries decay risk."
            )

        # SCENARIO 5: Normal conditions, long portfolio
        # Standard hedging consideration
        else:
            if portfolio_delta > portfolio_value * 0.5:  # Net long >50%
                signal_type = HedgeSignalType.BUY_VIX_CALL_SPREAD
                confidence = 55.0
                reasoning = (
                    f"VIX at {vix_spot:.1f} (normal range). "
                    f"Portfolio has net long delta exposure. "
                    f"IV-RV spread: {iv_rv_spread:.1f}pts (moderate). "
                    f"Consider baseline protection for tail risk."
                )
                recommended_action = (
                    f"Consider 1-2% of portfolio in VIX call spreads as tail hedge. "
                    f"Example: VIX {int(vix_spot + 10)}/{int(vix_spot + 25)} call spread. "
                    f"Accept this as insurance cost, not profit center."
                )
                risk_warning = (
                    "VIX hedges are expensive over time due to contango. "
                    "Budget ~3-5% annual cost for continuous protection. "
                    "Most periods, this hedge will lose money."
                )
            else:
                signal_type = HedgeSignalType.NO_ACTION
                confidence = 60.0
                reasoning = (
                    f"VIX at {vix_spot:.1f} (normal range). "
                    f"Portfolio delta exposure is manageable. "
                    f"No immediate hedging need."
                )
                recommended_action = "Monitor. No action required."
                risk_warning = "None"

        # Create signal
        signal = HedgeSignal(
            timestamp=now,
            signal_type=signal_type,
            confidence=confidence,
            vol_regime=vol_regime,
            reasoning=reasoning,
            recommended_action=recommended_action,
            risk_warning=risk_warning,
            metrics={
                'vix_spot': vix_spot,
                'vix_m1': vix_data.get('vix_m1', 0),
                'vix_m2': vix_data.get('vix_m2', 0),
                'term_structure_pct': term_structure,
                'iv_percentile': iv_percentile,
                'realized_vol_20d': realized_vol,
                'iv_rv_spread': iv_rv_spread,
                'spy_spot': spy_spot,
                'structure_type': vix_data.get('structure_type', 'unknown')
            }
        )

        # Log to database
        self._save_signal(signal)

        return signal

    def _save_signal(self, signal: HedgeSignal):
        """Save signal to database for tracking"""
        try:
            conn = get_connection()
            c = conn.cursor()

            c.execute("""
                INSERT INTO vix_hedge_signals (
                    signal_date, signal_time, signal_type, confidence,
                    vol_regime, vix_spot, vix_futures_m1, vix_futures_m2,
                    term_structure_pct, iv_percentile, realized_vol_20d,
                    iv_rv_spread, spy_spot, reasoning, recommended_action, risk_warning
                ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            """, (
                signal.timestamp.strftime('%Y-%m-%d'),
                signal.timestamp.strftime('%H:%M:%S'),
                signal.signal_type.value,
                signal.confidence,
                signal.vol_regime.value,
                signal.metrics.get('vix_spot', 0),
                signal.metrics.get('vix_m1', 0),
                signal.metrics.get('vix_m2', 0),
                signal.metrics.get('term_structure_pct', 0),
                signal.metrics.get('iv_percentile', 0),
                signal.metrics.get('realized_vol_20d', 0),
                signal.metrics.get('iv_rv_spread', 0),
                signal.metrics.get('spy_spot', 0),
                signal.reasoning,
                signal.recommended_action,
                signal.risk_warning
            ))

            conn.commit()
            conn.close()
        except Exception as e:
            print(f"Error saving signal: {e}")

    def get_signal_history(self, days: int = 30) -> pd.DataFrame:
        """Get historical signals"""
        conn = get_connection()
        df = pd.read_sql_query(f"""
            SELECT * FROM vix_hedge_signals
            WHERE signal_date >= CURRENT_DATE - INTERVAL '{days} days'
            ORDER BY signal_date DESC, signal_time DESC
        """, conn)
        conn.close()
        return df

    def print_signal_report(self, signal: HedgeSignal):
        """Print a formatted signal report"""
        print("\n" + "=" * 70)
        print("VIX HEDGE SIGNAL REPORT")
        print("=" * 70)
        print(f"Timestamp: {signal.timestamp.strftime('%Y-%m-%d %H:%M:%S CT')}")
        print(f"Signal: {signal.signal_type.value.upper()}")
        print(f"Confidence: {signal.confidence:.0f}%")
        print(f"Vol Regime: {signal.vol_regime.value.upper()}")

        print("\n--- MARKET DATA ---")
        m = signal.metrics
        print(f"VIX Spot: {m.get('vix_spot', 0):.2f}")
        print(f"VIX M1 Futures: {m.get('vix_m1', 0):.2f}")
        print(f"Term Structure: {m.get('term_structure_pct', 0):.1f}% ({m.get('structure_type', 'N/A')})")
        print(f"IV Percentile: {m.get('iv_percentile', 0):.0f}th")
        print(f"20-Day Realized Vol: {m.get('realized_vol_20d', 0):.1f}%")
        print(f"IV-RV Spread: {m.get('iv_rv_spread', 0):.1f} pts")
        print(f"SPY: ${m.get('spy_spot', 0):.2f}")

        print("\n--- ANALYSIS ---")
        print(signal.reasoning)

        print("\n--- RECOMMENDED ACTION ---")
        print(signal.recommended_action)

        print("\n--- RISK WARNING ---")
        print(signal.risk_warning)

        print("=" * 70 + "\n")


# Singleton instance
_vix_hedge_manager = None

def get_vix_hedge_manager() -> VIXHedgeManager:
    """Get singleton VIX hedge manager"""
    global _vix_hedge_manager
    if _vix_hedge_manager is None:
        _vix_hedge_manager = VIXHedgeManager()
    return _vix_hedge_manager


if __name__ == '__main__':
    # Generate and display a signal
    manager = get_vix_hedge_manager()

    print("\nGenerating VIX hedge signal...")
    signal = manager.generate_hedge_signal(
        portfolio_delta=75000,  # Long $75K delta
        portfolio_value=100000  # $100K portfolio
    )

    manager.print_signal_report(signal)

    # Show historical signals
    print("\nRecent Signal History:")
    history = manager.get_signal_history(7)
    if not history.empty:
        print(history[['signal_date', 'signal_type', 'confidence', 'vix_spot', 'iv_rv_spread']].to_string())
    else:
        print("No historical signals found.")
