/* Isolated full-history screen for the predeclared SPY debit-spread offense.
 * It is intentionally standalone: it establishes whether the offense itself
 * earns its cost before any combined-account promotion is considered.
 * No broker APIs, order endpoints, or production state are loaded. */
'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto'),zlib=require('node:zlib'),assert=require('node:assert/strict');
const BASE=process.env.THETADATA_BASE_URL||'http://thetadata-proxy:10000';
const CORE=require('./spark_flame_event_offense.cjs');
const ADAPTER=require('./spark_flame_event_offense_adapter.cjs');
const BASELINE=require('./flame_event_risk_sweep_20260930.cjs');
const {sessions,csv,clock,minute,MACRO_CALENDAR}=BASELINE;
const money=x=>Math.round((x+Number.EPSILON)*100)/100;
const sha=x=>crypto.createHash('sha256').update(x).digest('hex');
const emit=(event,fields={})=>console.log('OFFENSE '+JSON.stringify({event,utc:new Date().toISOString(),...fields}));
const STATE={stage:'created',completed:0,total:751,currentDay:null,requests:0,dataErrors:[]};
let pool=null,key=null;
const accounts=[];
for(const scenario of CORE.grid().filter(s=>s.family!=='overlay'))for(const [fillCase,slip] of Object.entries({natural:0,adverse3c:.03}))accounts.push({scenario,fillCase,slip,deposit:2000,equity:2000,history:[],trades:[],unresolved:[]});
function compact(a){if(!a.history.length)return;const old=a.packed?JSON.parse(zlib.gunzipSync(Buffer.from(a.packed,'base64')).toString()):[];old.push(...a.history);a.packed=zlib.gzipSync(JSON.stringify(old)).toString('base64');a.history=[];}
function rows(a){return (a.packed?JSON.parse(zlib.gunzipSync(Buffer.from(a.packed,'base64')).toString()):[]).concat(a.history);}
async function feed(endpoint,params){const u=new URL(BASE+endpoint);for(const [k,v] of Object.entries(params))u.searchParams.set(k,String(v));let last;for(let attempt=0;attempt<3;attempt++){try{STATE.requests++;const r=await fetch(u,{signal:AbortSignal.timeout(45000)});if(r.status===404)return [];if(!r.ok){last=Error(`http_${r.status}`);if(![429,500,502,503,504].includes(r.status))throw last;throw last;}if(r.headers.get('X-Market-Data-Provider')!=='thetadata')throw Error('unverified_provider');return csv(await r.text());}catch(error){last=error;const message=String(error.message);const permanent=/^http_/.test(message)&&!/^http_(429|500|502|503|504)$/.test(message);if(attempt===2||permanent)throw error;await new Promise(resolve=>setTimeout(resolve,1000*(attempt+1)));}}throw last;}
async function init(){let pg;try{pg=require('/tmp/sf3y-pg/node_modules/pg');}catch{require('node:child_process').execFileSync('npm',['install','--no-save','--no-package-lock','--prefix','/tmp/sf3y-pg','pg@8.16.3'],{stdio:'ignore'});pg=require('/tmp/sf3y-pg/node_modules/pg');}
 if(!process.env.RESEARCH_DATABASE_URL)throw Error('research_database_missing');pool=new pg.Pool({connectionString:process.env.RESEARCH_DATABASE_URL,max:1,ssl:true});if((await pool.query('select current_database() name')).rows[0].name!=='alphagex_backtest')throw Error('isolated_database_required');
 await pool.query('create table if not exists flame_event_offense_checkpoints (run_key text primary key,status text not null,completed integer not null,payload bytea not null,updated_at timestamptz not null default now())');
 key='flame-event-offense-20261002:'+(process.env.OFFENSE_CHECKPOINT_SOURCE_HASH||sha(fs.readFileSync(__filename)))+':'+sha(fs.readFileSync(path.join(__dirname,'spark_flame_event_offense.cjs')))+':'+sha(fs.readFileSync(path.join(__dirname,'spark_flame_event_offense_adapter.cjs')));
 const r=await pool.query('select payload from flame_event_offense_checkpoints where run_key=$1',[key]);if(r.rows.length){const saved=JSON.parse(zlib.gunzipSync(r.rows[0].payload));Object.assign(STATE,saved.state);if(STATE.stage==='blocked'&&(/^(http_(429|500|502|503|504)|fetch failed)$/.test(String(STATE.error)))){STATE.stage='running';STATE.error=null;STATE.dataErrors=[];}accounts.splice(0,accounts.length,...saved.accounts);for(const a of accounts)compact(a);emit('resumed',{completed:STATE.completed});}
}
async function save(){for(const a of accounts)compact(a);const body=zlib.gzipSync(JSON.stringify({state:STATE,accounts}));await pool.query('insert into flame_event_offense_checkpoints(run_key,status,completed,payload) values($1,$2,$3,$4) on conflict(run_key) do update set status=excluded.status,completed=excluded.completed,payload=excluded.payload,updated_at=now()',[key,STATE.stage,STATE.completed,body]);}
async function vix(day){const r=await pool.query("select extract(hour from ts)::int*60+extract(minute from ts)::int as minute_of_day,price from vix_index_price_3y where trade_date=$1::date order by ts",[day]);return new Map(r.rows.map(x=>[+x.minute_of_day,+x.price]));}
async function dayRun(day){const close=['2023-11-24','2024-07-03','2024-11-29','2024-12-24','2025-07-03','2025-11-28','2025-12-24'].includes(day)?780:960;const raw=await feed('/v3/stock/history/ohlc',{symbol:'SPY',date:day,interval:'1m',start_time:'09:30:00',end_time:clock(close),venue:'utp_cta'});const spy=new Map();for(const x of raw){const m=minute(x.timestamp||x.datetime,day);if(m<close)spy.set(m,{open:+x.open,high:+x.high,low:+x.low,close:+x.close});}if(!spy.size)throw Error('spy_minutes_missing');const tape=await vix(day),events=MACRO_CALENDAR[day]||[];const quoteCache=new Map();
 const quoteAt=async(signal,m)=>{const k=`${signal.right}:${signal.buyStrike}:${signal.sellStrike}`;let hit=quoteCache.get(k);if(!hit){const [buy,sell]=await Promise.all([feed('/v3/option/history/quote',{symbol:'SPY',right:signal.right,strike:signal.buyStrike,expiration:day,date:day,interval:'1m',start_time:clock(m),end_time:clock(close)}),feed('/v3/option/history/quote',{symbol:'SPY',right:signal.right,strike:signal.sellStrike,expiration:day,date:day,interval:'1m',start_time:clock(m),end_time:clock(close)})]);const map=rows=>new Map(rows.map(q=>[minute(q.timestamp||q.datetime,day),{bid:+q.bid,ask:+q.ask,bidSize:+q.bid_size,askSize:+q.ask}]));hit={buy:map(buy),sell:map(sell)};quoteCache.set(k,hit);}const buy=hit.buy.get(m),sell=hit.sell.get(m);return buy&&sell?{buy,sell}:null;};
 for(const a of accounts){const before=a.equity;const result=await ADAPTER.runDay({scenario:a.scenario,events,spy,vix:tape,close,dayStartEquity:before,cash:before,slip:a.slip,quoteAt});if(result.status==='unresolved'){a.unresolved.push({day,reason:result.reason});}const pnl=result.status==='closed'?result.pnl:0;a.equity=money(before+pnl);a.history.push([day,before,a.equity,pnl,result.status,result.reason||null]);if(result.status==='closed')a.trades.push({day,pnl,reason:result.exit.reason,n:result.entry.n,right:result.entry.right,entry:result.entry.entry,exit:result.exit.exit});}
}
function stats(a,period='full'){const d=rows(a).filter(x=>period==='full'||(period==='train'?x[0]<'2025-09-29':x[0]>='2025-09-29'));let peak=a.deposit,dd=0,worst=0,trades=0,losses=0;for(const x of d){peak=Math.max(peak,x[2]);dd=Math.max(dd,peak-x[2]);worst=Math.min(worst,x[3]);if(x[4]==='closed'){trades++;losses+=x[3]<0?1:0;}}const start=d[0]?.[1]??a.deposit,end=d.at(-1)?.[2]??start,pnl=money(end-start),bills=period==='full'?36:period==='train'?24:12;return {startingEquity:start,endingEquity:end,pnl,netAfterExternalSubscription:money(pnl-bills*50),trades,winRatePct:trades?money(100*(trades-losses)/trades):null,maxClosedDrawdown:money(dd),worstDay:worst,sessions:d.length};}
function report(){return accounts.map(a=>({id:a.scenario.id,scenario:a.scenario,fillCase:a.fillCase,full:stats(a),train:stats(a,'train'),validation:stats(a,'validation'),unresolved:a.unresolved.length})).sort((a,b)=>b.full.netAfterExternalSubscription-a.full.netAfterExternalSubscription);}
async function execute(){try{STATE.total=751;await init();if(STATE.stage==='completed'){emit('rankings',{rankings:report().slice(0,12)});return;}for(const day of sessions().slice(STATE.completed)){STATE.currentDay=day;await dayRun(day);STATE.completed++;STATE.stage='running';await save();emit('progress',{completed:STATE.completed,total:751,day,requests:STATE.requests,memoryMB:Math.round(process.memoryUsage().rss/1048576)});}STATE.stage='completed';await save();emit('finished',{completed:751,paths:accounts.length});emit('rankings',{rankings:report().slice(0,12)});}catch(e){STATE.stage='blocked';STATE.error=String(e.message);STATE.dataErrors.push({day:STATE.currentDay,error:STATE.error});try{await save();}catch{}emit('blocked',{...STATE});}}
function start(){assert.equal(accounts.length,96);const server=http.createServer((req,res)=>{if(req.url==='/health')return res.end('{"ok":true}');res.statusCode=403;res.end('{}');});server.listen(Number(process.env.PORT||10000),'0.0.0.0',()=>execute());}
if(require.main===module)start();module.exports={start,stats,accounts};
