/* Research-only Spark/Flame minute admission sweep. No broker or order APIs. */
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto'),zlib=require('node:zlib');
const SPEC={id:'spark-flame-minute-admission-sweep-20261001-v1',baselineKey:'spark-flame-current-3y-20260928-v2-reconstructed-gamma:75214ba4a85515a0e8700b9e388ec569bbb6222d927fb4f199ce0f6e8398e583:d86d19ebc95421cbc1cb1ac06a756554bf230967a47e3c6c1c2ef1b3be7d909f',trainingEnd:'2025-09-26',validationStart:'2025-09-29',scope:'pre-entry SPY/VIX minute admission only; matched baseline trade P&L; no claim of exit or hedge execution'};
const sha=x=>crypto.createHash('sha256').update(x).digest('hex');
let pool,checkpointKey,sessions=[],features=new Map(),baseline=new Map();
const STATE={stage:'created',run:SPEC.id,completed:0,total:0,currentDay:null,startedAt:null,updatedAt:null,error:null};
const scenarios=[];
function pg(){try{return require('/tmp/sf3y-pg/node_modules/pg');}catch{return require('/tmp/index-minute-import-pg/node_modules/pg');}}
function pct(a,b){return a&&b?(a/b-1)*100:NaN}
function grids(bot){const t=bot==='spark'?['11:05','1105']:['14:05','1405'];for(const vixMax of [14,16,18,20,24,30])for(const vix5Max of [.1,.3,.5,.8,1.2])for(const spy5Min of [-.6,-.4,-.25,-.1,0])for(const range15Max of [.12,.18,.25,.35,.5])scenarios.push({id:`${bot}-${vixMax}-${vix5Max}-${spy5Min}-${range15Max}`,bot,vixMax,vix5Max,spy5Min,range15Max,time:t[0],key:t[1],fills:{natural:newStat(bot),adverse3c:newStat(bot)}})}
function newStat(bot){const seed=bot==='spark'?5000:2000;return {equity:seed,peak:seed,pnl:0,trades:0,train:{pnl:0,trades:0,dd:0,peak:seed,equity:seed},validation:{pnl:0,trades:0,dd:0,peak:null,equity:null}}}
function tradeOK(s,f){const k=s.key,v=+f[`vix_${k}`],v5=+f[`vix_${k==='1105'?'1100':'1400'}`],p=+f[`spy_${k}`],p5=+f[`spy_${k==='1105'?'1100':'1400'}`],r=+f[`spy_range15_${k}`];return [v,v5,p,p5,r].every(Number.isFinite)&&v<=s.vixMax&&pct(v,v5)<=s.vix5Max&&pct(p,p5)>=s.spy5Min&&pct(r,p)<=s.range15Max}
function apply(stat,row,ok,train){const pnl=ok?+row[3]:0,trades=ok?((+row[8]||0)+(+row[9]||0)):0;stat.equity+=pnl;stat.peak=Math.max(stat.peak,stat.equity);stat.pnl+=pnl;stat.trades+=trades;const z=train?stat.train:stat.validation;if(!train&&z.equity===null){z.equity=stat.train.equity;z.peak=stat.train.peak;}z.equity+=pnl;z.peak=Math.max(z.peak,z.equity);z.pnl+=pnl;z.trades+=trades;z.dd=Math.min(z.dd,(z.equity-z.peak)/z.peak*100)}
function daily(bot,fill,day){return baseline.get(`${bot}|current_customer_package|${fill}`)?.get(day)}
async function save(){STATE.updatedAt=new Date().toISOString();const body=zlib.gzipSync(JSON.stringify({state:STATE,scenarios,sessions}));await pool.query('INSERT INTO spark_flame_research_checkpoints(run_key,status,completed,checkpoint) VALUES($1,$2,$3,$4) ON CONFLICT(run_key) DO UPDATE SET status=EXCLUDED.status,completed=EXCLUDED.completed,checkpoint=EXCLUDED.checkpoint,updated_at=NOW()',[checkpointKey,STATE.stage,STATE.completed,body])}
async function load(){const P=pg();pool=new P.Pool({connectionString:process.env.RESEARCH_DATABASE_URL,max:1,ssl:true});const db=await pool.query('SELECT current_database() name');if(db.rows[0].name!=='alphagex_backtest')throw Error('isolated_database_required');await pool.query('CREATE TABLE IF NOT EXISTS minute_controller_sweep_days(run_key text NOT NULL,day date NOT NULL,payload bytea NOT NULL,PRIMARY KEY(run_key,day))');checkpointKey=`${SPEC.id}:${sha(fs.readFileSync(__filename))}`;const prior=await pool.query('SELECT checkpoint FROM spark_flame_research_checkpoints WHERE run_key=$1',[checkpointKey]);if(prior.rows.length){const x=JSON.parse(zlib.gunzipSync(prior.rows[0].checkpoint));Object.assign(STATE,x.state);scenarios.splice(0,scenarios.length,...x.scenarios);sessions=x.sessions;return true}const b=await pool.query('SELECT checkpoint,status,completed FROM spark_flame_research_checkpoints WHERE run_key=$1',[SPEC.baselineKey]);if(b.rows[0]?.completed!==751||b.rows[0]?.status!=='completed_with_coverage_limits')throw Error('validated_baseline_missing');const input=JSON.parse(zlib.gunzipSync(b.rows[0].checkpoint));for(const a of input.accounts){if(a.profile==='current_customer_package')baseline.set(`${a.bot}|${a.profile}|${a.fillCase}`,new Map(a.history.map(r=>[r[0],r])))}const f=await pool.query(`WITH d AS (SELECT DISTINCT trade_date::date td FROM the_rock_3y),s AS (SELECT trade_date::date td,max(close) FILTER (WHERE ts::time='11:05') spy_1105,max(close) FILTER (WHERE ts::time='11:00') spy_1100,max(high) FILTER (WHERE ts::time BETWEEN '10:50' AND '11:05')-min(low) FILTER (WHERE ts::time BETWEEN '10:50' AND '11:05') spy_range15_1105,max(close) FILTER (WHERE ts::time='14:05') spy_1405,max(close) FILTER (WHERE ts::time='14:00') spy_1400,max(high) FILTER (WHERE ts::time BETWEEN '13:50' AND '14:05')-min(low) FILTER (WHERE ts::time BETWEEN '13:50' AND '14:05') spy_range15_1405 FROM spy_minute_3y GROUP BY 1),v AS (SELECT trade_date::date td,max(price) FILTER (WHERE ts::time='11:05') vix_1105,max(price) FILTER (WHERE ts::time='11:00') vix_1100,max(price) FILTER (WHERE ts::time='14:05') vix_1405,max(price) FILTER (WHERE ts::time='14:00') vix_1400 FROM vix_index_price_3y GROUP BY 1) SELECT d.td,s.*,v.* FROM d JOIN s USING(td) JOIN v USING(td) ORDER BY d.td`);sessions=f.rows.map(x=>String(x.td).slice(0,10));for(const x of f.rows)features.set(String(x.td).slice(0,10),x);if(sessions.length!==751)throw Error('minute_feature_coverage_incomplete');grids('spark');grids('flame');STATE.total=sessions.length}
function snapshot(){const byBot={};for(const bot of ['spark','flame']){const base=scenarios.filter(x=>x.bot===bot);const robust=base.filter(s=>['natural','adverse3c'].every(f=>s.fills[f].train.pnl>=0&&s.fills[f].train.dd>=-100)).sort((a,b)=>(b.fills.natural.train.pnl+b.fills.adverse3c.train.pnl)-(a.fills.natural.train.pnl+a.fills.adverse3c.train.pnl));byBot[bot]={scenarios:base.length,topTraining:robust.slice(0,10).map(s=>({parameters:{vixMax:s.vixMax,vix5Max:s.vix5Max,spy5Min:s.spy5Min,range15Max:s.range15Max},natural:s.fills.natural,adverse:s.fills.adverse3c})),robustTrainingCount:robust.length}}return {spec:SPEC,status:STATE,engineHash:sha(fs.readFileSync(__filename)),byBot}}
async function execute(){try{STATE.startedAt=new Date().toISOString();STATE.stage='loading';const resumed=await load();if(resumed&&STATE.stage==='completed')return;STATE.stage='running';for(const day of sessions.slice(STATE.completed)){STATE.currentDay=day;const f=features.get(day),train=day<=SPEC.trainingEnd;for(const s of scenarios)for(const fill of ['natural','adverse3c']){const row=daily(s.bot,fill,day);if(!row)throw Error(`baseline_day_missing:${s.bot}:${fill}:${day}`);const wasTraded=(+row[8]||0)+(+row[9]||0)>0;apply(s.fills[fill],row,!wasTraded||tradeOK(s,f),train)}STATE.completed++;await pool.query('BEGIN');try{await pool.query('INSERT INTO minute_controller_sweep_days(run_key,day,payload) VALUES($1,$2,$3) ON CONFLICT(run_key,day) DO UPDATE SET payload=EXCLUDED.payload',[checkpointKey,day,zlib.gzipSync(JSON.stringify({day,completed:STATE.completed}))]);await save();await pool.query('COMMIT')}catch(e){await pool.query('ROLLBACK');throw e}if(STATE.completed%10===0)console.log('MINUTE_SWEEP '+JSON.stringify({event:'progress',completed:STATE.completed,total:STATE.total,day}))}STATE.stage='completed';await save();console.log('MINUTE_SWEEP '+JSON.stringify({event:'completed',completed:STATE.completed,total:STATE.total}))}catch(e){STATE.stage='blocked';STATE.error=e.message;try{await save()}catch{};console.error('MINUTE_SWEEP_FATAL',e.stack||e);process.exitCode=1}}
function start(){http.createServer((q,r)=>{r.setHeader('Content-Type','application/json');r.setHeader('Cache-Control','no-store');if(q.url==='/'||q.url==='/status')return r.end(JSON.stringify({...STATE,scenarios:scenarios.length,engineHash:sha(fs.readFileSync(__filename))}));if(q.url==='/report')return r.end(JSON.stringify(snapshot()));r.statusCode=404;r.end(JSON.stringify({error:'not_found'}))}).listen(Number(process.env.PORT||10000),'0.0.0.0',()=>execute())}
module.exports={start,tradeOK,grids};if(require.main===module)start();
