'use client'

import { useState } from 'react'
import { Calendar, ChevronDown, ChevronUp, RefreshCw } from 'lucide-react'
import { useDailyTradingPlan } from '@/lib/hooks/useMarketData'

export default function DailyTradingPlan() {
  const [expanded, setExpanded] = useState(true)
  const { data, error, isLoading, isValidating, mutate } = useDailyTradingPlan()

  const formatGeneratedAt = (dateStr: string) => {
    return new Date(dateStr).toLocaleString('en-US', {
      hour: 'numeric',
      minute: '2-digit',
      hour12: true,
      month: 'short',
      day: 'numeric',
      timeZone: 'America/Chicago'
    })
  }

  const plan = data?.data?.plan || ''
  const generatedAtRaw = data?.data?.generated_at || ''
  const generatedAt = generatedAtRaw ? formatGeneratedAt(generatedAtRaw) : ''
  const loading = isLoading && !data
  const refreshing = isValidating

  return (
    <div className="card bg-gradient-to-r from-success/5 to-transparent border border-success/20">
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2">
          <Calendar className="w-5 h-5 text-success" />
          <h3 className="text-lg font-semibold text-text-primary">Daily Trading Plan</h3>
        </div>
        <div className="flex items-center gap-2">
          {generatedAt && (
            <span className="text-xs text-text-muted">{generatedAt}</span>
          )}
          <button
            onClick={() => mutate()}
            disabled={refreshing}
            className="p-2 hover:bg-success/10 rounded-lg transition-colors"
            title="Refresh plan"
          >
            <RefreshCw className={`w-4 h-4 text-success ${refreshing ? 'animate-spin' : ''}`} />
          </button>
          <button
            onClick={() => setExpanded(!expanded)}
            className="p-2 hover:bg-success/10 rounded-lg transition-colors"
          >
            {expanded ? (
              <ChevronUp className="w-4 h-4 text-success" />
            ) : (
              <ChevronDown className="w-4 h-4 text-success" />
            )}
          </button>
        </div>
      </div>

      {expanded && (
        <div className="space-y-3">
          {loading ? (
            <div className="animate-pulse space-y-2">
              <div className="h-4 bg-background-hover rounded w-full"></div>
              <div className="h-4 bg-background-hover rounded w-5/6"></div>
              <div className="h-4 bg-background-hover rounded w-4/6"></div>
              <div className="h-4 bg-background-hover rounded w-full"></div>
              <div className="h-4 bg-background-hover rounded w-3/4"></div>
            </div>
          ) : error ? (
            <div className="p-4 bg-danger/10 border border-danger/20 rounded-lg">
              <p className="text-danger text-sm">{error.message || 'Unable to load trading plan'}</p>
            </div>
          ) : (
            <>
              <div className="prose prose-sm max-w-none max-h-96 overflow-y-auto pr-2">
                <div className="text-text-primary whitespace-pre-wrap leading-relaxed">
                  {plan || 'Daily trading plan temporarily unavailable. Please try refreshing.'}
                </div>
              </div>

              <div className="mt-4 pt-4 border-t border-border flex items-center justify-between">
                <div className="flex items-center gap-2 text-xs text-text-muted">
                  <div className="w-2 h-2 bg-success rounded-full"></div>
                  <span>Generated by Claude • Cached across pages</span>
                </div>
                <button
                  onClick={() => mutate()}
                  disabled={refreshing}
                  className="text-xs text-success hover:underline font-medium disabled:opacity-50"
                >
                  {refreshing ? 'Refreshing...' : 'Refresh Plan'}
                </button>
              </div>
            </>
          )}
        </div>
      )}

      {!expanded && (
        <p className="text-sm text-text-secondary">
          Click to expand your personalized daily trading plan...
        </p>
      )}
    </div>
  )
}
