"""
VIX Volatility Hedge Manager - Signal Generation for Portfolio Protection
==========================================================================

This module generates SIGNALS for VIX-based hedging strategies.
It does NOT auto-execute trades because VIX hedging requires human judgment.

KEY PRINCIPLES:
1. VIX options track VIX FUTURES, not VIX spot
2. VIX futures are in contango ~80% of the time (constant theta bleed)
3. Correlation between SPY/SPX and VIX is non-linear and asymmetric
4. When you need protection most (crashes), spreads blow out 500%+

STRATEGIES MONITORED:
1. IV Percentile vs Realized Vol spread
2. VIX Term Structure (contango/backwardation)
3. VVIX (volatility of VIX) for timing
4. Cross-asset correlation regime

OUTPUT: Signal generator, NOT autonomous executor
"""

import logging
import threading
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from typing import Dict, List, Optional, Tuple
from enum import Enum
from zoneinfo import ZoneInfo
from database_adapter import get_connection
import numpy as np
import pandas as pd

# Configure logger
logger = logging.getLogger(__name__)

CENTRAL_TZ = ZoneInfo("America/Chicago")

# UNIFIED Data Provider (Tradier primary, Polygon fallback)
try:
    from data.unified_data_provider import get_data_provider, get_vix
    UNIFIED_DATA_AVAILABLE = True
except ImportError:
    UNIFIED_DATA_AVAILABLE = False

# Legacy Polygon fallback
try:
    from data.polygon_data_fetcher import polygon_fetcher
    POLYGON_AVAILABLE = True
except ImportError:
    POLYGON_AVAILABLE = False
    polygon_fetcher = None  # Define as None to prevent NameError


class HedgeSignalType(Enum):
    """Types of hedge signals"""
    BUY_VIX_CALLS = "buy_vix_calls"           # Buy protection
    BUY_VIX_CALL_SPREAD = "buy_vix_call_spread"  # Cheaper protection
    SELL_VIX_PUTS = "sell_vix_puts"           # Sell vol (dangerous)
    REDUCE_HEDGE = "reduce_hedge"             # Take off protection
    NO_ACTION = "no_action"                   # Stay flat
    ROLL_HEDGE = "roll_hedge"                 # Roll existing position


class VolRegime(Enum):
    """Volatility regime classification"""
    VERY_LOW = "very_low"       # VIX < 12 - complacent, protection cheap
    LOW = "low"                 # VIX 12-15 - normal low
    NORMAL = "normal"           # VIX 15-20 - typical conditions
    ELEVATED = "elevated"       # VIX 20-25 - heightened concern
    HIGH = "high"               # VIX 25-35 - fear mode
    EXTREME = "extreme"         # VIX > 35 - panic


@dataclass
class HedgeSignal:
    """A hedge signal generated by the manager"""
    timestamp: datetime
    signal_type: HedgeSignalType
    confidence: float  # 0-100
    vol_regime: VolRegime
    reasoning: str
    recommended_action: str
    risk_warning: str
    metrics: Dict = field(default_factory=dict)


class VIXHedgeManager:
    """
    VIX-based volatility hedge signal generator for SPY/SPX portfolios.

    CRITICAL: This generates SIGNALS only, not trades.
    Human review required before execution.
    """

    def __init__(self):
        """Initialize the VIX hedge manager"""
        self.lookback_days = 252  # 1 year for IV percentile
        self.rv_window = 20  # 20-day realized vol
        self._db_available = False
        self._tables_initialized = False

        # Try to initialize database tables (but don't fail if unavailable)
        try:
            self._ensure_tables()
            self._db_available = True
            self._tables_initialized = True
        except Exception as e:
            logger.warning(f"VIX Hedge Manager: Database not available ({type(e).__name__}), running without persistence")

        # VIX thresholds
        self.vol_thresholds = {
            'very_low': 12,
            'low': 15,
            'normal': 20,
            'elevated': 25,
            'high': 35
        }

        # Signal generation parameters
        self.iv_rv_spread_threshold = 5.0  # Points difference for signal
        self.term_structure_threshold = 3.0  # Contango/backwardation threshold

        logger.info("VIX Hedge Manager initialized (SIGNAL GENERATOR ONLY)")

    def _ensure_tables(self):
        """
        Verify VIX hedge tables exist.
        NOTE: Tables are now defined in db/config_and_database.py (single source of truth).
        Tables expected: vix_hedge_signals, vix_hedge_positions
        """
        # Verify connection works and required tables exist
        conn = get_connection()
        try:
            c = conn.cursor()
            # Check if vix_hedge_signals table exists
            c.execute("""
                SELECT EXISTS (
                    SELECT FROM information_schema.tables
                    WHERE table_name = 'vix_hedge_signals'
                )
            """)
            signals_exists = c.fetchone()[0]

            if not signals_exists:
                logger.warning("VIX hedge_signals table not found - signals will not be persisted")

            conn.close()
            logger.debug("VIX hedge tables verification complete")
        except Exception as e:
            conn.close()
            raise e

    def get_vix_data(self) -> Dict:
        """
        Get comprehensive VIX data for analysis.

        Returns:
            Dict with VIX spot, futures, term structure, etc.

        NOTE ON VIX FUTURES:
        - VIX M1/M2 futures require direct futures data feed
        - If unavailable, we estimate using historical contango patterns:
          - M1 typically trades ~5% above spot in normal markets
          - M2 typically trades ~8% above spot
          - During stress, VIX can go into backwardation (spot > futures)
        - The 'is_estimated' flag indicates when estimates are used
        """
        try:
            from data.vix_fetcher import get_vix_with_source
            vix_spot, vix_source = get_vix_with_source()

            # Try to get VVIX (volatility of VIX) for timing signals
            vvix = None
            vvix_source = 'none'
            if POLYGON_AVAILABLE and polygon_fetcher:
                try:
                    vvix = polygon_fetcher.get_current_price('I:VVIX')
                    if vvix and vvix > 0:
                        vvix_source = 'polygon'
                except Exception:
                    pass  # VVIX is optional, continue without it

            # VIX FUTURES ESTIMATION
            # CRITICAL: This is an estimate - real futures data would be better
            # In normal markets: M1 ~5% contango, M2 ~8% contango
            # During stress (VIX > 30): Often flat or backwardation
            # During complacency (VIX < 15): Steep contango (7-10%)

            is_estimated = True  # Flag for frontend to show "estimated" label
            vix_m1 = None
            vix_m2 = None

            # Dynamic contango estimation based on VIX level
            if vix_spot >= 35:
                # Panic/crisis - often backwardation or flat
                contango_m1 = -0.02  # -2% (backwardation)
                contango_m2 = -0.01  # Slight backwardation
            elif vix_spot >= 25:
                # High stress - reduced contango
                contango_m1 = 0.02  # 2%
                contango_m2 = 0.04  # 4%
            elif vix_spot >= 20:
                # Elevated - normal contango
                contango_m1 = 0.05  # 5%
                contango_m2 = 0.08  # 8%
            elif vix_spot >= 15:
                # Normal - typical contango
                contango_m1 = 0.05  # 5%
                contango_m2 = 0.08  # 8%
            else:
                # Low/complacent - steep contango
                contango_m1 = 0.07  # 7%
                contango_m2 = 0.12  # 12%

            vix_m1 = vix_spot * (1 + contango_m1)
            vix_m2 = vix_spot * (1 + contango_m2)

            # Calculate term structure
            term_structure_m1 = contango_m1 * 100  # As percentage
            term_structure_m2 = contango_m2 * 100

            # Determine structure type
            if term_structure_m1 > 1:
                structure_type = "contango"
            elif term_structure_m1 < -1:
                structure_type = "backwardation"
            else:
                structure_type = "flat"

            # VIX stress classification for trading decisions
            if vix_spot >= 35:
                vix_stress_level = "extreme"
                position_size_multiplier = 0.25  # 75% reduction
            elif vix_spot >= 28:
                vix_stress_level = "high"
                position_size_multiplier = 0.50  # 50% reduction
            elif vix_spot >= 22:
                vix_stress_level = "elevated"
                position_size_multiplier = 0.75  # 25% reduction
            else:
                vix_stress_level = "normal"
                position_size_multiplier = 1.0  # No reduction

            return {
                'vix_spot': vix_spot,
                'vix_source': vix_source,
                'vix_m1': vix_m1,
                'vix_m2': vix_m2,
                'is_estimated': is_estimated,
                'term_structure_m1_pct': term_structure_m1,
                'term_structure_m2_pct': term_structure_m2,
                'structure_type': structure_type,
                'vvix': vvix,
                'vvix_source': vvix_source,
                'vix_stress_level': vix_stress_level,
                'position_size_multiplier': position_size_multiplier,
                'timestamp': datetime.now(CENTRAL_TZ).isoformat()
            }

        except Exception as e:
            logger.warning(f"Error getting live VIX data: {e} - using fallback defaults")
            # Return fallback data so signal generation can continue
            # Mark as estimated/fallback so frontend can show warning
            return {
                'vix_spot': 18.0,  # Reasonable market average
                'vix_source': 'fallback',
                'vix_m1': 18.9,    # ~5% contango
                'vix_m2': 19.4,    # ~8% contango
                'is_estimated': True,
                'is_fallback': True,  # Additional flag to indicate data source failure
                'term_structure_m1_pct': 5.0,
                'term_structure_m2_pct': 8.0,
                'structure_type': 'contango',
                'vvix': None,
                'vvix_source': 'none',
                'vix_stress_level': 'normal',
                'position_size_multiplier': 1.0,
                'timestamp': datetime.now(CENTRAL_TZ).isoformat(),
                'error': str(e)
            }

    def calculate_iv_percentile(self, vix_current: float) -> float:
        """
        Calculate current VIX percentile over lookback period.

        Uses historical VIX data to determine where current VIX sits.
        """
        try:
            # Get historical VIX data (only if Polygon available)
            data = None
            if POLYGON_AVAILABLE and polygon_fetcher:
                data = polygon_fetcher.get_price_history(
                    'I:VIX',
                    days=self.lookback_days,
                    timeframe='day'
                )

            if data is None or len(data) < 50:
                # Fallback: use typical VIX distribution
                # Historical mean ~17, std ~6
                from scipy import stats
                percentile = stats.percentileofscore([12, 14, 16, 18, 20, 22, 25, 30, 35], vix_current)
                return percentile

            # Calculate percentile
            vix_history = data['Close'].values
            percentile = (np.sum(vix_history <= vix_current) / len(vix_history)) * 100

            return percentile

        except Exception as e:
            logger.warning(f"Error calculating IV percentile: {e}")
            # Estimate based on typical VIX range
            if vix_current < 12:
                return 5
            elif vix_current < 15:
                return 20
            elif vix_current < 18:
                return 40
            elif vix_current < 22:
                return 60
            elif vix_current < 28:
                return 80
            else:
                return 95

    def calculate_realized_vol(self, symbol: str = 'SPY') -> float:
        """
        Calculate 20-day realized volatility for SPY.

        Returns annualized volatility percentage.
        """
        try:
            # Get historical price data (only if Polygon available)
            data = None
            if POLYGON_AVAILABLE and polygon_fetcher:
                data = polygon_fetcher.get_price_history(
                    symbol,
                    days=30,
                    timeframe='day'
                )

            if data is None or len(data) < self.rv_window:
                return 18.0  # Default estimate

            # Calculate log returns
            returns = np.log(data['Close'] / data['Close'].shift(1)).dropna()

            # Use last 20 days
            recent_returns = returns.tail(self.rv_window)

            # Annualized volatility
            rv = recent_returns.std() * np.sqrt(252) * 100

            return rv

        except Exception as e:
            logger.warning(f"Error calculating realized vol: {e}")
            return 18.0

    def get_vol_regime(self, vix: float) -> VolRegime:
        """Classify current volatility regime"""
        if vix < self.vol_thresholds['very_low']:
            return VolRegime.VERY_LOW
        elif vix < self.vol_thresholds['low']:
            return VolRegime.LOW
        elif vix < self.vol_thresholds['normal']:
            return VolRegime.NORMAL
        elif vix < self.vol_thresholds['elevated']:
            return VolRegime.ELEVATED
        elif vix < self.vol_thresholds['high']:
            return VolRegime.HIGH
        else:
            return VolRegime.EXTREME

    def generate_hedge_signal(
        self,
        portfolio_delta: float = 0,
        portfolio_value: float = 100000
    ) -> HedgeSignal:
        """
        Generate a hedge signal based on current market conditions.

        Args:
            portfolio_delta: Current portfolio delta exposure
            portfolio_value: Total portfolio value

        Returns:
            HedgeSignal with recommendation
        """
        now = datetime.now(CENTRAL_TZ)

        # Gather data
        vix_data = self.get_vix_data()
        vix_spot = vix_data.get('vix_spot', 18.0)

        iv_percentile = self.calculate_iv_percentile(vix_spot)
        realized_vol = self.calculate_realized_vol('SPY')

        vol_regime = self.get_vol_regime(vix_spot)
        term_structure = vix_data.get('term_structure_m1_pct', 5.0)

        # Calculate IV - RV spread
        iv_rv_spread = vix_spot - realized_vol

        # Get SPY price for context
        spy_spot = 500.0  # Reasonable default for SPY
        if POLYGON_AVAILABLE and polygon_fetcher:
            try:
                spy_spot = polygon_fetcher.get_current_price('SPY') or 500.0
            except Exception:
                pass  # Use default

        # Decision logic
        signal_type = HedgeSignalType.NO_ACTION
        confidence = 50.0
        reasoning = ""
        recommended_action = ""
        risk_warning = ""

        # SCENARIO 1: Very low VIX + IV cheap relative to RV
        # This is when protection is cheap - good time to buy
        if vol_regime in [VolRegime.VERY_LOW, VolRegime.LOW] and iv_rv_spread < 2:
            signal_type = HedgeSignalType.BUY_VIX_CALL_SPREAD
            confidence = 75.0
            reasoning = (
                f"VIX at {vix_spot:.1f} ({iv_percentile:.0f}th percentile) - PROTECTION IS CHEAP. "
                f"IV-RV spread only {iv_rv_spread:.1f}pts. "
                f"Term structure in {vix_data.get('structure_type', 'contango')} ({term_structure:.1f}%). "
                f"This is an opportune time to add portfolio protection at low cost."
            )
            recommended_action = (
                f"Consider buying VIX call spread: "
                f"Buy VIX {int(vix_spot + 5)} calls, Sell VIX {int(vix_spot + 15)} calls. "
                f"Target 1-2 months expiration. "
                f"Cost should be ~0.5-1.5% of portfolio value."
            )
            risk_warning = (
                "WARNING: VIX options decay via contango roll. "
                "Protection cost ~3-5% per month if held through roll. "
                "Set maximum holding period."
            )

        # SCENARIO 2: Elevated VIX + IV expensive relative to RV
        # Reduce or avoid adding protection
        elif vol_regime in [VolRegime.ELEVATED, VolRegime.HIGH] and iv_rv_spread > 8:
            signal_type = HedgeSignalType.REDUCE_HEDGE
            confidence = 65.0
            reasoning = (
                f"VIX at {vix_spot:.1f} ({iv_percentile:.0f}th percentile) - PROTECTION IS EXPENSIVE. "
                f"IV-RV spread {iv_rv_spread:.1f}pts (RV only {realized_vol:.1f}%). "
                f"Protection costs are elevated - poor risk/reward for new hedges."
            )
            recommended_action = (
                f"Do NOT add new VIX protection at these levels. "
                f"If holding existing hedges, consider taking profit if >30% gain. "
                f"Wait for VIX pullback below {self.vol_thresholds['normal']} before adding."
            )
            risk_warning = (
                "WARNING: High VIX often mean-reverts. "
                "Buying protection here risks paying peak prices. "
                "However, if a major event is imminent, protection may still be warranted."
            )

        # SCENARIO 3: Extreme VIX (panic)
        # DO NOT buy protection here
        elif vol_regime == VolRegime.EXTREME:
            signal_type = HedgeSignalType.NO_ACTION
            confidence = 80.0
            reasoning = (
                f"VIX at {vix_spot:.1f} (EXTREME) - DO NOT ADD PROTECTION HERE. "
                f"Panic conditions - spreads are widest, prices are highest. "
                f"If you don't have protection now, it's too late for this move."
            )
            recommended_action = (
                "DO NOT buy VIX protection during panic. "
                "Instead, consider: (1) Reduce equity exposure, (2) Wait for VIX to normalize, "
                "(3) Use SPY/SPX put spreads which may have tighter markets."
            )
            risk_warning = (
                "CRITICAL: VIX options during panic have 500%+ wider spreads. "
                "Any protection bought here will immediately lose 20-30% to bid/ask. "
                "This is NOT the time to buy insurance."
            )

        # SCENARIO 4: Backwardation (VIX futures below spot)
        # Unusual - usually during stress or right after spike
        elif term_structure < -2:
            signal_type = HedgeSignalType.ROLL_HEDGE
            confidence = 60.0
            reasoning = (
                f"VIX term structure in BACKWARDATION ({term_structure:.1f}%). "
                f"This is unusual and typically occurs during/after stress events. "
                f"Backwardation means futures decay POSITIVELY - hedges actually gain from roll."
            )
            recommended_action = (
                "If holding VIX protection, consider EXTENDING duration. "
                "Roll from near-month to further-out expiration. "
                "Backwardation is favorable for VIX longs."
            )
            risk_warning = (
                "Backwardation usually resolves within days to weeks. "
                "VIX spike may have already occurred - late entry carries decay risk."
            )

        # SCENARIO 5: Normal conditions, long portfolio
        # Standard hedging consideration
        else:
            if portfolio_delta > portfolio_value * 0.5:  # Net long >50%
                signal_type = HedgeSignalType.BUY_VIX_CALL_SPREAD
                confidence = 55.0
                reasoning = (
                    f"VIX at {vix_spot:.1f} (normal range). "
                    f"Portfolio has net long delta exposure. "
                    f"IV-RV spread: {iv_rv_spread:.1f}pts (moderate). "
                    f"Consider baseline protection for tail risk."
                )
                recommended_action = (
                    f"Consider 1-2% of portfolio in VIX call spreads as tail hedge. "
                    f"Example: VIX {int(vix_spot + 10)}/{int(vix_spot + 25)} call spread. "
                    f"Accept this as insurance cost, not profit center."
                )
                risk_warning = (
                    "VIX hedges are expensive over time due to contango. "
                    "Budget ~3-5% annual cost for continuous protection. "
                    "Most periods, this hedge will lose money."
                )
            else:
                signal_type = HedgeSignalType.NO_ACTION
                confidence = 60.0
                reasoning = (
                    f"VIX at {vix_spot:.1f} (normal range). "
                    f"Portfolio delta exposure is manageable. "
                    f"No immediate hedging need."
                )
                recommended_action = "Monitor. No action required."
                risk_warning = "None"

        # Create signal
        signal = HedgeSignal(
            timestamp=now,
            signal_type=signal_type,
            confidence=confidence,
            vol_regime=vol_regime,
            reasoning=reasoning,
            recommended_action=recommended_action,
            risk_warning=risk_warning,
            metrics={
                'vix_spot': vix_spot,
                'vix_m1': vix_data.get('vix_m1', 0),
                'vix_m2': vix_data.get('vix_m2', 0),
                'term_structure_pct': term_structure,
                'iv_percentile': iv_percentile,
                'realized_vol_20d': realized_vol,
                'iv_rv_spread': iv_rv_spread,
                'spy_spot': spy_spot,
                'structure_type': vix_data.get('structure_type', 'unknown'),
                'vix_source': vix_data.get('vix_source', 'unknown'),
                'is_fallback': vix_data.get('is_fallback', False),
            }
        )

        # Log to database
        self._save_signal(signal)

        return signal

    def _save_signal(self, signal: HedgeSignal):
        """Save signal to database for tracking"""
        if not self._db_available:
            return  # Skip saving if database not available

        try:
            conn = get_connection()
            c = conn.cursor()

            # Ensure new columns exist (migration)
            try:
                c.execute("""
                    ALTER TABLE vix_hedge_signals
                    ADD COLUMN IF NOT EXISTS vix_source VARCHAR(50) DEFAULT 'unknown',
                    ADD COLUMN IF NOT EXISTS is_fallback BOOLEAN DEFAULT FALSE
                """)
                conn.commit()
            except Exception:
                conn.rollback()  # Column might already exist in different format

            # Get fallback status from metrics
            is_fallback = signal.metrics.get('is_fallback', False)
            vix_source = signal.metrics.get('vix_source', 'unknown')

            c.execute("""
                INSERT INTO vix_hedge_signals (
                    signal_date, signal_time, signal_type, confidence,
                    vol_regime, vix_spot, vix_futures_m1, vix_futures_m2,
                    term_structure_pct, iv_percentile, realized_vol_20d,
                    iv_rv_spread, spy_spot, reasoning, recommended_action, risk_warning,
                    vix_source, is_fallback
                ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            """, (
                signal.timestamp.strftime('%Y-%m-%d'),
                signal.timestamp.strftime('%H:%M:%S'),
                signal.signal_type.value,
                signal.confidence,
                signal.vol_regime.value,
                signal.metrics.get('vix_spot', 0),
                signal.metrics.get('vix_m1', 0),
                signal.metrics.get('vix_m2', 0),
                signal.metrics.get('term_structure_pct', 0),
                signal.metrics.get('iv_percentile', 0),
                signal.metrics.get('realized_vol_20d', 0),
                signal.metrics.get('iv_rv_spread', 0),
                signal.metrics.get('spy_spot', 0),
                signal.reasoning,
                signal.recommended_action,
                signal.risk_warning,
                vix_source,
                is_fallback
            ))

            conn.commit()
            conn.close()

            source_info = f" (source: {vix_source})" if vix_source != 'unknown' else ""
            fallback_info = " [FALLBACK DATA]" if is_fallback else ""
            logger.info(f"VIX hedge signal saved: {signal.signal_type.value}{source_info}{fallback_info}")
        except Exception as e:
            logger.error(f"Error saving VIX signal: {e}")

    def get_signal_history(self, days: int = 30) -> pd.DataFrame:
        """Get historical signals"""
        if not self._db_available:
            return pd.DataFrame()  # Return empty DataFrame if no database

        try:
            conn = get_connection()
            df = pd.read_sql_query(f"""
                SELECT * FROM vix_hedge_signals
                WHERE signal_date >= CURRENT_DATE - INTERVAL '{days} days'
                ORDER BY signal_date DESC, signal_time DESC
            """, conn)
            conn.close()
            return df
        except Exception as e:
            logger.warning(f"Error getting signal history: {e}")
            return pd.DataFrame()

    def print_signal_report(self, signal: HedgeSignal):
        """Print a formatted signal report"""
        print("\n" + "=" * 70)
        print("VIX HEDGE SIGNAL REPORT")
        print("=" * 70)
        print(f"Timestamp: {signal.timestamp.strftime('%Y-%m-%d %H:%M:%S CT')}")
        print(f"Signal: {signal.signal_type.value.upper()}")
        print(f"Confidence: {signal.confidence:.0f}%")
        print(f"Vol Regime: {signal.vol_regime.value.upper()}")

        print("\n--- MARKET DATA ---")
        m = signal.metrics
        print(f"VIX Spot: {m.get('vix_spot', 0):.2f}")
        print(f"VIX M1 Futures: {m.get('vix_m1', 0):.2f}")
        print(f"Term Structure: {m.get('term_structure_pct', 0):.1f}% ({m.get('structure_type', 'N/A')})")
        print(f"IV Percentile: {m.get('iv_percentile', 0):.0f}th")
        print(f"20-Day Realized Vol: {m.get('realized_vol_20d', 0):.1f}%")
        print(f"IV-RV Spread: {m.get('iv_rv_spread', 0):.1f} pts")
        print(f"SPY: ${m.get('spy_spot', 0):.2f}")

        print("\n--- ANALYSIS ---")
        print(signal.reasoning)

        print("\n--- RECOMMENDED ACTION ---")
        print(signal.recommended_action)

        print("\n--- RISK WARNING ---")
        print(signal.risk_warning)

        print("=" * 70 + "\n")


# Singleton instance with thread-safe initialization
_vix_hedge_manager = None
_vix_hedge_manager_lock = threading.Lock()

def get_vix_hedge_manager() -> VIXHedgeManager:
    """Get singleton VIX hedge manager (thread-safe)"""
    global _vix_hedge_manager
    if _vix_hedge_manager is None:
        with _vix_hedge_manager_lock:
            # Double-check locking pattern
            if _vix_hedge_manager is None:
                _vix_hedge_manager = VIXHedgeManager()
    return _vix_hedge_manager


if __name__ == '__main__':
    # Generate and display a signal
    manager = get_vix_hedge_manager()

    print("\nGenerating VIX hedge signal...")
    signal = manager.generate_hedge_signal(
        portfolio_delta=75000,  # Long $75K delta
        portfolio_value=100000  # $100K portfolio
    )

    manager.print_signal_report(signal)

    # Show historical signals
    print("\nRecent Signal History:")
    history = manager.get_signal_history(7)
    if not history.empty:
        print(history[['signal_date', 'signal_type', 'confidence', 'vix_spot', 'iv_rv_spread']].to_string())
    else:
        print("No historical signals found.")
