"""
Daily Manna API routes - Economic news with faith-based devotionals.

Provides daily economic news with Bible study and morning prayer generated by Claude AI.
"""

import os
import json
import hashlib
from datetime import datetime, date
from typing import Optional, Dict, Any, List

from fastapi import APIRouter, HTTPException

router = APIRouter(prefix="/api/daily-manna", tags=["Daily Manna"])

# Cache for daily content (one generation per day)
_daily_cache: Dict[str, Any] = {}
_cache_date: Optional[date] = None


def get_cache_key() -> str:
    """Generate cache key for today's content."""
    return datetime.now().strftime("%Y-%m-%d")


def get_cached_content() -> Optional[Dict[str, Any]]:
    """Get cached content if it's from today."""
    global _daily_cache, _cache_date
    today = date.today()
    if _cache_date == today and _daily_cache:
        return _daily_cache
    return None


def set_cached_content(content: Dict[str, Any]) -> None:
    """Cache content for today."""
    global _daily_cache, _cache_date
    _daily_cache = content
    _cache_date = date.today()


def get_daily_scriptures() -> List[Dict[str, str]]:
    """
    Get a rotating set of scriptures for economic/provision themes.
    Returns different verses based on day of year.
    """
    scriptures = [
        {
            "reference": "Philippians 4:19",
            "text": "And my God will meet all your needs according to the riches of his glory in Christ Jesus.",
            "theme": "God's Provision"
        },
        {
            "reference": "Proverbs 3:9-10",
            "text": "Honor the Lord with your wealth, with the firstfruits of all your crops; then your barns will be filled to overflowing.",
            "theme": "Honoring God with Wealth"
        },
        {
            "reference": "Matthew 6:33",
            "text": "But seek first his kingdom and his righteousness, and all these things will be given to you as well.",
            "theme": "Kingdom Priorities"
        },
        {
            "reference": "Deuteronomy 8:18",
            "text": "But remember the Lord your God, for it is he who gives you the ability to produce wealth.",
            "theme": "Source of Prosperity"
        },
        {
            "reference": "Proverbs 21:5",
            "text": "The plans of the diligent lead to profit as surely as haste leads to poverty.",
            "theme": "Diligent Planning"
        },
        {
            "reference": "Ecclesiastes 11:2",
            "text": "Invest in seven ventures, yes, in eight; you do not know what disaster may come upon the land.",
            "theme": "Diversification"
        },
        {
            "reference": "Luke 16:10",
            "text": "Whoever can be trusted with very little can also be trusted with much.",
            "theme": "Faithful Stewardship"
        },
        {
            "reference": "Proverbs 22:7",
            "text": "The rich rule over the poor, and the borrower is slave to the lender.",
            "theme": "Wisdom with Debt"
        },
        {
            "reference": "1 Timothy 6:10",
            "text": "For the love of money is a root of all kinds of evil.",
            "theme": "Heart Posture"
        },
        {
            "reference": "Malachi 3:10",
            "text": "Bring the whole tithe into the storehouse... and see if I will not throw open the floodgates of heaven.",
            "theme": "Generosity"
        },
        {
            "reference": "Proverbs 13:11",
            "text": "Dishonest money dwindles away, but whoever gathers money little by little makes it grow.",
            "theme": "Patient Accumulation"
        },
        {
            "reference": "Matthew 25:21",
            "text": "Well done, good and faithful servant! You have been faithful with a few things; I will put you in charge of many things.",
            "theme": "Faithful Investment"
        },
        {
            "reference": "James 1:5",
            "text": "If any of you lacks wisdom, you should ask God, who gives generously to all without finding fault.",
            "theme": "Divine Wisdom"
        },
        {
            "reference": "Psalm 37:25",
            "text": "I was young and now I am old, yet I have never seen the righteous forsaken or their children begging bread.",
            "theme": "God's Faithfulness"
        },
        {
            "reference": "Proverbs 11:24-25",
            "text": "One person gives freely, yet gains even more; another withholds unduly, but comes to poverty. A generous person will prosper.",
            "theme": "Generous Living"
        },
        {
            "reference": "Romans 13:8",
            "text": "Let no debt remain outstanding, except the continuing debt to love one another.",
            "theme": "Financial Freedom"
        },
        {
            "reference": "Hebrews 13:5",
            "text": "Keep your lives free from the love of money and be content with what you have, because God has said, 'Never will I leave you; never will I forsake you.'",
            "theme": "Contentment"
        },
        {
            "reference": "Proverbs 27:23-24",
            "text": "Be sure you know the condition of your flocks, give careful attention to your herds; for riches do not endure forever.",
            "theme": "Diligent Oversight"
        },
        {
            "reference": "2 Corinthians 9:8",
            "text": "And God is able to bless you abundantly, so that in all things at all times, having all that you need, you will abound in every good work.",
            "theme": "Abundant Blessing"
        },
        {
            "reference": "Matthew 6:19-21",
            "text": "Do not store up for yourselves treasures on earth... But store up for yourselves treasures in heaven... For where your treasure is, there your heart will be also.",
            "theme": "Eternal Perspective"
        },
    ]

    # Rotate based on day of year
    day_of_year = datetime.now().timetuple().tm_yday
    index = day_of_year % len(scriptures)

    # Return today's scripture plus two related ones
    return [
        scriptures[index],
        scriptures[(index + 7) % len(scriptures)],
        scriptures[(index + 13) % len(scriptures)],
    ]


def fetch_economic_news() -> List[Dict[str, Any]]:
    """
    Fetch today's economic news headlines.
    Uses market data context from the trading system.
    """
    try:
        # Try to get market context from the trading system
        from backend.api.dependencies import api_client, UNIFIED_DATA_AVAILABLE, get_vix

        news_items = []
        today = datetime.now()

        # Get VIX for market sentiment
        vix_value = None
        if UNIFIED_DATA_AVAILABLE and get_vix:
            try:
                vix_value = get_vix()
            except:
                pass

        # Get SPY data for market context
        spy_data = None
        if api_client:
            try:
                spy_data = api_client.get_net_gamma('SPY')
            except:
                pass

        # Generate contextual market news based on actual data
        if spy_data:
            spot_price = spy_data.get('spot_price', 0)
            net_gex = spy_data.get('net_gex', 0)
            flip_point = spy_data.get('flip_point', 0)

            # Determine market regime
            if net_gex > 0:
                regime = "positive gamma"
                regime_impact = "Markets are positioned for stability with dealer hedging dampening volatility."
            else:
                regime = "negative gamma"
                regime_impact = "Markets may see amplified moves as dealer hedging adds to directional momentum."

            news_items.append({
                "headline": f"S&P 500 Trading at ${spot_price:.2f} in {regime.title()} Environment",
                "summary": regime_impact,
                "category": "Market Structure",
                "timestamp": today.isoformat(),
                "impact": "high"
            })

            # Flip point analysis
            if spot_price > flip_point:
                position = "above"
                outlook = "Bullish positioning favored with calls dominating."
            else:
                position = "below"
                outlook = "Bearish pressure possible with puts dominating."

            news_items.append({
                "headline": f"SPY Trading {position.title()} Gamma Flip Point at ${flip_point:.2f}",
                "summary": outlook,
                "category": "Technical",
                "timestamp": today.isoformat(),
                "impact": "medium"
            })

        # VIX context
        if vix_value:
            if vix_value < 15:
                vix_outlook = "Extremely low volatility suggests complacency - consider protection."
                impact = "low"
            elif vix_value < 20:
                vix_outlook = "Normal volatility levels indicate balanced market conditions."
                impact = "medium"
            elif vix_value < 25:
                vix_outlook = "Elevated fear levels suggest caution with aggressive positions."
                impact = "high"
            else:
                vix_outlook = "High fear in markets - opportunities for patient investors, but risk management critical."
                impact = "high"

            news_items.append({
                "headline": f"VIX at {vix_value:.2f} - Market Volatility {'Subdued' if vix_value < 18 else 'Elevated'}",
                "summary": vix_outlook,
                "category": "Volatility",
                "timestamp": today.isoformat(),
                "impact": impact
            })

        # Add general economic context items
        day_name = today.strftime("%A")

        # Day-specific context
        economic_context = {
            "Monday": {
                "headline": "Markets Open After Weekend - Positioning for the Week Ahead",
                "summary": "Monday sessions often see repositioning as traders digest weekend news and set up for the week.",
                "category": "Market Dynamics"
            },
            "Tuesday": {
                "headline": "Mid-Week Trading Momentum Building",
                "summary": "Tuesday typically sees follow-through from Monday's price action with increasing volume.",
                "category": "Market Dynamics"
            },
            "Wednesday": {
                "headline": "Fed Watch Wednesday - FOMC Minutes and Policy Signals",
                "summary": "Mid-week often brings Fed communications and economic data releases.",
                "category": "Federal Reserve"
            },
            "Thursday": {
                "headline": "Weekly Jobless Claims and Economic Data Day",
                "summary": "Thursday brings weekly unemployment data and pre-Friday positioning.",
                "category": "Economic Data"
            },
            "Friday": {
                "headline": "End of Week - Options Expiration and Gamma Effects",
                "summary": "Weekly options expiration creates unique gamma dynamics, especially for 0DTE strategies.",
                "category": "Options"
            },
            "Saturday": {
                "headline": "Weekend Analysis - Preparing for Monday's Open",
                "summary": "Use this time for study and preparation while markets are closed.",
                "category": "Preparation"
            },
            "Sunday": {
                "headline": "Week Ahead Preview - Global Events and Earnings",
                "summary": "Review the economic calendar and prepare your trading plan for the week.",
                "category": "Planning"
            }
        }

        day_context = economic_context.get(day_name, economic_context["Monday"])
        news_items.append({
            "headline": day_context["headline"],
            "summary": day_context["summary"],
            "category": day_context["category"],
            "timestamp": today.isoformat(),
            "impact": "medium"
        })

        return news_items

    except Exception as e:
        # Return minimal news if fetching fails
        return [{
            "headline": "Markets Active - Check Live Data for Current Conditions",
            "summary": "Economic conditions are evolving. Use the GEX dashboard for real-time market structure analysis.",
            "category": "General",
            "timestamp": datetime.now().isoformat(),
            "impact": "medium"
        }]


async def generate_devotional_with_claude(
    news_items: List[Dict[str, Any]],
    scriptures: List[Dict[str, str]]
) -> Dict[str, Any]:
    """
    Use Claude AI to generate a Bible study and morning prayer
    based on today's economic news and selected scriptures.
    """
    try:
        import anthropic

        api_key = os.environ.get('ANTHROPIC_API_KEY')
        if not api_key:
            return {
                "bible_study": "API key not configured. Please set ANTHROPIC_API_KEY.",
                "morning_prayer": "Lord, guide our steps today as we navigate the markets with wisdom and integrity. Amen.",
                "reflection_questions": ["How can I honor God with my financial decisions today?"]
            }

        # Build context from news and scriptures
        news_summary = "\n".join([
            f"- {item['headline']}: {item['summary']}"
            for item in news_items[:3]
        ])

        scripture_text = "\n".join([
            f"- {s['reference']}: \"{s['text']}\" (Theme: {s['theme']})"
            for s in scriptures
        ])

        today = datetime.now().strftime("%A, %B %d, %Y")

        prompt = f"""You are a wise Christian financial advisor and pastor who helps believers integrate their faith with their investment and trading activities. Today is {today}.

Today's Economic Context:
{news_summary}

Today's Scriptures:
{scripture_text}

Please create a "Daily Manna" devotional that:

1. **Bible Study** (2-3 paragraphs): Connect today's scriptures to the current economic conditions. Help the reader understand how biblical principles apply to their trading and investing. Be practical and encouraging, not preachy. Reference specific market conditions when relevant.

2. **Morning Prayer** (1 paragraph): Write a sincere morning prayer that asks for wisdom in financial decisions, protection from greed and fear, and the heart to honor God with resources. Make it personal and heartfelt.

3. **Reflection Questions** (3 questions): Provide thoughtful questions for the reader to consider as they approach the markets today.

4. **Key Insight** (1-2 sentences): A practical takeaway that bridges faith and finance for today.

Format your response as JSON with these keys:
- bible_study: The Bible study text (can use markdown for formatting)
- morning_prayer: The prayer text
- reflection_questions: Array of 3 questions
- key_insight: The practical takeaway
- theme: A 2-3 word theme for today's devotional"""

        client = anthropic.Anthropic(api_key=api_key)

        message = client.messages.create(
            model="claude-sonnet-4-5-20250929",
            max_tokens=2000,
            messages=[
                {"role": "user", "content": prompt}
            ]
        )

        response_text = message.content[0].text if message.content else "{}"

        # Parse JSON response
        try:
            # Find JSON in response (might be wrapped in markdown code blocks)
            json_match = response_text
            if "```json" in response_text:
                json_match = response_text.split("```json")[1].split("```")[0]
            elif "```" in response_text:
                json_match = response_text.split("```")[1].split("```")[0]

            devotional = json.loads(json_match.strip())
            return devotional
        except json.JSONDecodeError:
            # If JSON parsing fails, extract content manually
            return {
                "bible_study": response_text,
                "morning_prayer": "Lord, grant us wisdom and discernment as we steward the resources You have entrusted to us. Help us to honor You in all our financial decisions. Amen.",
                "reflection_questions": [
                    "How can I honor God with my trading decisions today?",
                    "Am I trading from a place of faith or fear?",
                    "What would faithful stewardship look like in today's market conditions?"
                ],
                "key_insight": "True wealth is found in faithful stewardship, not just profitable trades.",
                "theme": "Faithful Stewardship"
            }

    except Exception as e:
        return {
            "bible_study": f"Unable to generate devotional content. Error: {str(e)}",
            "morning_prayer": "Heavenly Father, even when technology fails, Your wisdom remains. Guide our steps today. Amen.",
            "reflection_questions": [
                "How can I find peace in uncertain markets?",
                "What does faithfulness look like in my trading?",
                "How can I be a blessing to others through my financial success?"
            ],
            "key_insight": "God's provision is not dependent on market conditions.",
            "theme": "Trust in Providence"
        }


@router.get("/news")
async def get_economic_news():
    """
    Get today's economic news and market context.

    Returns current market conditions, VIX levels, and relevant economic context
    formatted for spiritual reflection.
    """
    try:
        news_items = fetch_economic_news()

        return {
            "success": True,
            "data": {
                "news": news_items,
                "date": datetime.now().strftime("%A, %B %d, %Y"),
                "timestamp": datetime.now().isoformat()
            }
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/scriptures")
async def get_daily_scriptures_endpoint():
    """
    Get today's selected scriptures for reflection.

    Returns 3 rotating scriptures focused on wealth, stewardship,
    and God's provision - different each day.
    """
    try:
        scriptures = get_daily_scriptures()

        return {
            "success": True,
            "data": {
                "scriptures": scriptures,
                "date": datetime.now().strftime("%A, %B %d, %Y")
            }
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/devotional")
async def get_devotional(force_refresh: bool = False):
    """
    Get today's AI-generated devotional.

    Generates a Bible study and morning prayer based on current
    economic conditions and daily scriptures.

    The devotional is cached for the day unless force_refresh=true.
    """
    try:
        # Check cache first
        if not force_refresh:
            cached = get_cached_content()
            if cached:
                return {
                    "success": True,
                    "data": cached,
                    "cached": True
                }

        # Generate fresh content
        news_items = fetch_economic_news()
        scriptures = get_daily_scriptures()
        devotional = await generate_devotional_with_claude(news_items, scriptures)

        # Combine all content
        content = {
            "devotional": devotional,
            "scriptures": scriptures,
            "news": news_items,
            "date": datetime.now().strftime("%A, %B %d, %Y"),
            "timestamp": datetime.now().isoformat()
        }

        # Cache for the day
        set_cached_content(content)

        return {
            "success": True,
            "data": content,
            "cached": False
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/today")
async def get_daily_manna(force_refresh: bool = False):
    """
    Get complete Daily Manna content for today.

    This is the main endpoint that returns everything:
    - Today's economic news/market context
    - Selected scriptures
    - AI-generated Bible study
    - Morning prayer
    - Reflection questions

    Content is cached for the day (one generation per day).
    Use force_refresh=true to regenerate.
    """
    try:
        # Check cache first
        if not force_refresh:
            cached = get_cached_content()
            if cached:
                return {
                    "success": True,
                    "data": cached,
                    "cached": True,
                    "message": "Today's manna is ready! Content generated fresh each morning."
                }

        # Generate fresh content
        news_items = fetch_economic_news()
        scriptures = get_daily_scriptures()
        devotional = await generate_devotional_with_claude(news_items, scriptures)

        # Combine all content
        content = {
            "devotional": devotional,
            "scriptures": scriptures,
            "news": news_items,
            "date": datetime.now().strftime("%A, %B %d, %Y"),
            "timestamp": datetime.now().isoformat(),
            "greeting": get_daily_greeting()
        }

        # Cache for the day
        set_cached_content(content)

        return {
            "success": True,
            "data": content,
            "cached": False,
            "message": "Fresh manna prepared! May it nourish your soul and guide your trading."
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


def get_daily_greeting() -> str:
    """Get a contextual greeting based on time of day."""
    hour = datetime.now().hour

    if hour < 5:
        return "Night owl or early bird? Either way, God's mercies are new every morning."
    elif hour < 12:
        return "Good morning! May this Daily Manna nourish your soul before the market opens."
    elif hour < 17:
        return "Good afternoon! Take a moment to center yourself amidst the market activity."
    elif hour < 21:
        return "Good evening! Reflect on today's trades with gratitude and wisdom."
    else:
        return "Rest well tonight. Tomorrow brings new opportunities to honor God with your resources."
