/**
 * Full-package day-row parity, ROUND 8 (K=0.1, variant G): drives
 * evaluateDepositFloorCap + evaluateFastStartUpsize (B1) + evaluateCalmUpsize +
 * evaluateFlintCushion (with the ROUND 8 host-committed-risk netting) together,
 * exactly reproducing `customer_protection_finalK.py`'s simulate_package_k() day loop
 * (K=0.1, variant G, N=3 — B1 pre-cushion on ALL deposits/both bots, house-money
 * calm-post gated on deposit >= $4,000), and checks 100% day-row parity against a
 * fixture generated by calling `customer_protection_finalK.simulate_package_k`
 * DIRECTLY (not a transcription) — n_host, n_flint, floor, triggered, and
 * calm_applied on every day, all 4 cells (FLAME $2,000/$4,242, SPARK $5,000/$7,500),
 * sequential and stateful (peak-equity ratchet + trigger state carried day-to-day).
 *
 * KNOWN DISCREPANCY, documented not hidden: the static `customer_package_fixtures_K.json`
 * the coordinator pointed to disagrees with `customer_protection_finalK.py`'s OWN
 * `simulate_package_k` function (called directly, fresh process, same inputs) on
 * 362/974 days for BOTH FLAME cells (0/974 for SPARK) — the static file appears stale
 * for FLAME. This fixture was generated by calling the live function directly, which
 * is the more rigorous ground truth (verified two independent ways: a hand transcription
 * of the source and a direct import both agree with each other and disagree with the
 * static file at the exact same days). Flagged in the PR for the coordinator to confirm.
 *
 * The fixture carries a `calm` boolean per day (already the VIX<=0.70 result) rather
 * than a raw ratio; this test converts it to a deterministic surrogate ratio (0.5 for
 * calm, 0.9 for not) purely so evaluateFastStartUpsize/evaluateCalmUpsize's own ratio
 * comparison has something to compare against — the ceiling comparison itself is
 * covered directly with explicit values elsewhere in this file.
 */
import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import {
  evaluateDepositFloorCap,
  evaluateFastStartUpsize,
  evaluateCalmUpsize,
  evaluateFlintCushion,
  currentFloorLevelCents,
} from '../contracts'

const VIX_CEILING = 0.70
const MARGIN_CENTS = 5_000
const MIN_DEPOSIT_FOR_CALM_POST = 400_000
const FLOOR_K = 0.1
const TRIGGER_N = 3

interface FixtureDay {
  day_index: number
  equity_cents: number
  deposit_cents: number
  ml_cents: number
  cand: boolean
  calm: boolean
  flint_cand: boolean
  flint_ml_cents: number
  n_host: number
  n_flint: number
  floor_cents: number
  triggered_after: boolean
  calm_applied: boolean
}

interface FixtureCell {
  deposit: number
  use_b1_pre: boolean
  use_calm_post: boolean
  days: FixtureDay[]
}

const fixturePath = join(__dirname, 'fixtures', 'final-package-parity.json')
const fixture = JSON.parse(readFileSync(fixturePath, 'utf8')) as Record<string, FixtureCell>

describe('final customer package — 100% day-row parity vs customer_protection_finalK.py (ROUND 8, K=0.1/G)', () => {
  it('the fixture is non-trivial across all 4 cells (pre- and post-trigger, calm-applied, and FLINT days all present)', () => {
    expect(Object.keys(fixture)).toEqual(['FLAME_D2000', 'FLAME_D4242', 'SPARK_D5000', 'SPARK_D7500'])
    for (const cell of Object.values(fixture)) {
      expect(cell.days.length).toBeGreaterThan(300)
      expect(cell.days.some((d) => d.calm_applied)).toBe(true)
      expect(cell.days.some((d) => d.n_flint > 0)).toBe(true)
      expect(cell.days.some((d) => d.triggered_after)).toBe(true)
      expect(cell.days.some((d) => !d.triggered_after)).toBe(true)
    }
  })

  for (const [label, cell] of Object.entries(fixture)) {
    it(`${label}: n_host, n_flint, floor, triggered, and calm_applied match on every day`, () => {
      let triggered = false
      let peakEquityCents = cell.deposit * 100

      for (const day of cell.days) {
        // Peak-equity ratchet runs EVERY day (the sim's `peak_equity = max(peak_equity,
        // equity)` executes unconditionally each iteration, not just on host-candidate
        // days — a FLINT-only day still moves equity via flint_pnl).
        peakEquityCents = Math.max(peakEquityCents, day.equity_cents)

        let nHost = 0
        let calmApplied = false
        let floorLevelCents = triggered ? currentFloorLevelCents(day.deposit_cents, peakEquityCents, true, FLOOR_K) : day.deposit_cents

        if (day.cand) {
          const desiredContracts = Math.floor((day.equity_cents * 20) / 100 / day.ml_cents)
          const floorResult = evaluateDepositFloorCap({
            equityCents: day.equity_cents, depositCents: day.deposit_cents, peakEquityCents,
            maxLossCentsPerContract: day.ml_cents, marginCents: MARGIN_CENTS,
            pct: 20, desiredContracts, triggered, triggerN: TRIGGER_N, floorK: FLOOR_K,
          })
          nHost = floorResult.contracts
          floorLevelCents = floorResult.floorLevelCents
          const vixRatio = day.calm ? 0.5 : 0.9

          if (!floorResult.triggeredForSizing && cell.use_b1_pre) {
            const b1 = evaluateFastStartUpsize({
              triggeredForSizing: floorResult.triggeredForSizing, baseContracts: nHost,
              vixRatio, vixCeiling: VIX_CEILING,
            })
            if (b1.extraContract) { nHost += 1; calmApplied = true }
          } else if (floorResult.triggeredForSizing && cell.use_calm_post) {
            const calm = evaluateCalmUpsize({
              equityCents: day.equity_cents, depositCents: day.deposit_cents, protectLevelCents: floorLevelCents,
              baseContracts: nHost, maxLossCentsPerContract: day.ml_cents, marginCents: MARGIN_CENTS,
              vixRatio, vixCeiling: VIX_CEILING, minDepositCentsForUpsize: MIN_DEPOSIT_FOR_CALM_POST,
            })
            if (calm.extraContract) { nHost += 1; calmApplied = true }
          }

          triggered = triggered || floorResult.triggeredNow
          peakEquityCents = floorResult.nextPeakEquityCents
        }

        // ROUND 8: FLINT's gate nets the host leg's OWN committed risk this same day
        // (n_host * ml, no margin — the sim's literal formula) before checking FLINT's
        // own max loss + margin.
        let nFlint = 0
        if (day.flint_cand && day.flint_ml_cents > 0) {
          const hostCommittedCents = nHost * day.ml_cents
          const flintGate = evaluateFlintCushion({
            equityCents: day.equity_cents, protectLevelCents: floorLevelCents, hostCommittedCents,
            maxLossCents: day.flint_ml_cents, marginCents: MARGIN_CENTS,
          })
          nFlint = flintGate.eligible ? 1 : 0
        }

        const ctx = `${label} day_index=${day.day_index} cand=${day.cand} triggered=${triggered}`
        expect(nHost, `n_host mismatch: ${ctx}`).toBe(day.n_host)
        expect(nFlint, `n_flint mismatch: ${ctx}`).toBe(day.n_flint)
        expect(floorLevelCents, `floor mismatch: ${ctx}`).toBe(day.floor_cents)
        expect(triggered, `triggered mismatch: ${ctx}`).toBe(day.triggered_after)
        expect(calmApplied, `calm_applied mismatch: ${ctx}`).toBe(day.calm_applied)
      }
    })
  }
})
