"""
125+ encouraging Bible verses for daily market open rotation.
Each verse is selected for traders facing uncertainty, risk, and the need for discipline.
"""

VERSES = [
    # === COURAGE & STRENGTH (25) ===
    {"reference": "Joshua 1:9", "text": "Have I not commanded you? Be strong and courageous. Do not be afraid; do not be discouraged, for the LORD your God will be with you wherever you go."},
    {"reference": "Isaiah 41:10", "text": "So do not fear, for I am with you; do not be dismayed, for I am your God. I will strengthen you and help you; I will uphold you with my righteous right hand."},
    {"reference": "Deuteronomy 31:6", "text": "Be strong and courageous. Do not be afraid or terrified because of them, for the LORD your God goes with you; he will never leave you nor forsake you."},
    {"reference": "2 Timothy 1:7", "text": "For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline."},
    {"reference": "Psalm 27:1", "text": "The LORD is my light and my salvation — whom shall I fear? The LORD is the stronghold of my life — of whom shall I be afraid?"},
    {"reference": "Isaiah 40:31", "text": "But those who hope in the LORD will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint."},
    {"reference": "Psalm 46:1", "text": "God is our refuge and strength, an ever-present help in trouble."},
    {"reference": "Philippians 4:13", "text": "I can do all this through him who gives me strength."},
    {"reference": "Psalm 18:32", "text": "It is God who arms me with strength and keeps my way secure."},
    {"reference": "Isaiah 40:29", "text": "He gives strength to the weary and increases the power of the weak."},
    {"reference": "Psalm 28:7", "text": "The LORD is my strength and my shield; my heart trusts in him, and he helps me. My heart leaps for joy, and with my song I praise him."},
    {"reference": "Ephesians 6:10", "text": "Finally, be strong in the Lord and in his mighty power."},
    {"reference": "1 Chronicles 28:20", "text": "Be strong and courageous, and do the work. Do not be afraid or discouraged, for the LORD God is with you. He will not fail you or forsake you."},
    {"reference": "Psalm 31:24", "text": "Be strong and take heart, all you who hope in the LORD."},
    {"reference": "Nehemiah 8:10", "text": "Do not grieve, for the joy of the LORD is your strength."},
    {"reference": "Psalm 73:26", "text": "My flesh and my heart may fail, but God is the strength of my heart and my portion forever."},
    {"reference": "2 Corinthians 12:9", "text": "But he said to me, 'My grace is sufficient for you, for my power is made perfect in weakness.'"},
    {"reference": "Psalm 138:3", "text": "When I called, you answered me; you greatly emboldened me."},
    {"reference": "Isaiah 12:2", "text": "Surely God is my salvation; I will trust and not be afraid. The LORD, the LORD himself, is my strength and my defense."},
    {"reference": "Habakkuk 3:19", "text": "The Sovereign LORD is my strength; he makes my feet like the feet of a deer, he enables me to tread on the heights."},
    {"reference": "Psalm 118:6", "text": "The LORD is with me; I will not be afraid. What can mere mortals do to me?"},
    {"reference": "Romans 8:31", "text": "What, then, shall we say in response to these things? If God is for us, who can be against us?"},
    {"reference": "Psalm 56:3-4", "text": "When I am afraid, I put my trust in you. In God, whose word I praise — in God I trust and am not afraid."},
    {"reference": "Isaiah 54:17", "text": "No weapon forged against you will prevail, and you will refute every tongue that accuses you."},
    {"reference": "Psalm 144:1", "text": "Praise be to the LORD my Rock, who trains my hands for war, my fingers for battle."},

    # === TRUST & FAITH (25) ===
    {"reference": "Proverbs 3:5-6", "text": "Trust in the LORD with all your heart and lean not on your own understanding; in all your ways submit to him, and he will make your paths straight."},
    {"reference": "Jeremiah 29:11", "text": "For I know the plans I have for you, declares the LORD, plans to prosper you and not to harm you, plans to give you hope and a future."},
    {"reference": "Psalm 37:5", "text": "Commit your way to the LORD; trust in him and he will do this."},
    {"reference": "Hebrews 11:1", "text": "Now faith is confidence in what we hope for and assurance about what we do not see."},
    {"reference": "Romans 8:28", "text": "And we know that in all things God works for the good of those who love him, who have been called according to his purpose."},
    {"reference": "Psalm 9:10", "text": "Those who know your name trust in you, for you, LORD, have never forsaken those who seek you."},
    {"reference": "Proverbs 16:3", "text": "Commit to the LORD whatever you do, and he will establish your plans."},
    {"reference": "Isaiah 26:3", "text": "You will keep in perfect peace those whose minds are steadfast, because they trust in you."},
    {"reference": "Psalm 125:1", "text": "Those who trust in the LORD are like Mount Zion, which cannot be shaken but endures forever."},
    {"reference": "Matthew 17:20", "text": "Truly I tell you, if you have faith as small as a mustard seed, you can say to this mountain, 'Move from here to there,' and it will move. Nothing will be impossible for you."},
    {"reference": "Mark 11:24", "text": "Therefore I tell you, whatever you ask for in prayer, believe that you have received it, and it will be yours."},
    {"reference": "Psalm 62:8", "text": "Trust in him at all times, you people; pour out your hearts to him, for God is our refuge."},
    {"reference": "Proverbs 29:25", "text": "Fear of man will prove to be a snare, but whoever trusts in the LORD is kept safe."},
    {"reference": "Psalm 20:7", "text": "Some trust in chariots and some in horses, but we trust in the name of the LORD our God."},
    {"reference": "Nahum 1:7", "text": "The LORD is good, a refuge in times of trouble. He cares for those who trust in him."},
    {"reference": "2 Corinthians 5:7", "text": "For we live by faith, not by sight."},
    {"reference": "Psalm 37:3", "text": "Trust in the LORD and do good; dwell in the land and enjoy safe pasture."},
    {"reference": "Romans 15:13", "text": "May the God of hope fill you with all joy and peace as you trust in him, so that you may overflow with hope by the power of the Holy Spirit."},
    {"reference": "Hebrews 11:6", "text": "And without faith it is impossible to please God, because anyone who comes to him must believe that he exists and that he rewards those who earnestly seek him."},
    {"reference": "Psalm 112:7", "text": "They will have no fear of bad news; their hearts are steadfast, trusting in the LORD."},
    {"reference": "Isaiah 30:15", "text": "In repentance and rest is your salvation, in quietness and trust is your strength."},
    {"reference": "Psalm 143:8", "text": "Let the morning bring me word of your unfailing love, for I have put my trust in you. Show me the way I should go, for to you I entrust my life."},
    {"reference": "Matthew 6:34", "text": "Therefore do not worry about tomorrow, for tomorrow will worry about itself. Each day has enough trouble of its own."},
    {"reference": "Psalm 40:4", "text": "Blessed is the one who trusts in the LORD, who does not look to the proud, to those who turn aside to false gods."},
    {"reference": "Lamentations 3:25", "text": "The LORD is good to those whose hope is in him, to the one who seeks him."},

    # === PATIENCE & PERSEVERANCE (20) ===
    {"reference": "James 1:2-4", "text": "Consider it pure joy, my brothers and sisters, whenever you face trials of many kinds, because you know that the testing of your faith produces perseverance. Let perseverance finish its work so that you may be mature and complete, not lacking anything."},
    {"reference": "Galatians 6:9", "text": "Let us not become weary in doing good, for at the proper time we will reap a harvest if we do not give up."},
    {"reference": "Romans 5:3-4", "text": "Not only so, but we also glory in our sufferings, because we know that suffering produces perseverance; perseverance, character; and character, hope."},
    {"reference": "Hebrews 10:36", "text": "You need to persevere so that when you have done the will of God, you will receive what he has promised."},
    {"reference": "Psalm 27:14", "text": "Wait for the LORD; be strong and take heart and wait for the LORD."},
    {"reference": "Psalm 33:20", "text": "We wait in hope for the LORD; he is our help and our shield."},
    {"reference": "Habakkuk 2:3", "text": "For the revelation awaits an appointed time; it speaks of the end and will not prove false. Though it linger, wait for it; it will certainly come and will not delay."},
    {"reference": "Romans 12:12", "text": "Be joyful in hope, patient in affliction, faithful in prayer."},
    {"reference": "Hebrews 12:1", "text": "Therefore, since we are surrounded by such a great cloud of witnesses, let us throw off everything that hinders and the sin that so easily entangles. And let us run with perseverance the race marked out for us."},
    {"reference": "James 5:11", "text": "As you know, we count as blessed those who have persevered. You have heard of Job's perseverance and have seen what the Lord finally brought about."},
    {"reference": "Psalm 37:7", "text": "Be still before the LORD and wait patiently for him; do not fret when people succeed in their ways."},
    {"reference": "Colossians 3:23", "text": "Whatever you do, work at it with all your heart, as working for the Lord, not for human masters."},
    {"reference": "1 Corinthians 15:58", "text": "Therefore, my dear brothers and sisters, stand firm. Let nothing move you. Always give yourselves fully to the work of the Lord, because you know that your labor in the Lord is not in vain."},
    {"reference": "2 Thessalonians 3:13", "text": "And as for you, brothers and sisters, never tire of doing what is good."},
    {"reference": "Psalm 130:5", "text": "I wait for the LORD, my whole being waits, and in his word I put my hope."},
    {"reference": "Ecclesiastes 7:8", "text": "The end of a matter is better than its beginning, and patience is better than pride."},
    {"reference": "Proverbs 14:29", "text": "Whoever is patient has great understanding, but one who is quick-tempered displays folly."},
    {"reference": "Romans 8:25", "text": "But if we hope for what we do not yet have, we wait for it patiently."},
    {"reference": "2 Peter 1:6", "text": "And to knowledge, self-control; and to self-control, perseverance; and to perseverance, godliness."},
    {"reference": "Psalm 40:1", "text": "I waited patiently for the LORD; he turned to me and heard my cry."},

    # === WISDOM & GUIDANCE (20) ===
    {"reference": "James 1:5", "text": "If any of you lacks wisdom, you should ask God, who gives generously to all without finding fault, and it will be given to you."},
    {"reference": "Proverbs 2:6", "text": "For the LORD gives wisdom; from his mouth come knowledge and understanding."},
    {"reference": "Proverbs 4:7", "text": "The beginning of wisdom is this: Get wisdom. Though it cost all you have, get understanding."},
    {"reference": "Psalm 32:8", "text": "I will instruct you and teach you in the way you should go; I will counsel you with my loving eye on you."},
    {"reference": "Proverbs 16:16", "text": "How much better to get wisdom than gold, to get insight rather than silver!"},
    {"reference": "Proverbs 3:13-14", "text": "Blessed are those who find wisdom, those who gain understanding, for she is more profitable than silver and yields better returns than gold."},
    {"reference": "Proverbs 19:20", "text": "Listen to advice and accept discipline, and at the end you will be counted among the wise."},
    {"reference": "Colossians 3:16", "text": "Let the message of Christ dwell among you richly as you teach and admonish one another with all wisdom."},
    {"reference": "Proverbs 15:22", "text": "Plans fail for lack of counsel, but with many advisers they succeed."},
    {"reference": "Proverbs 24:3-4", "text": "By wisdom a house is built, and through understanding it is established; through knowledge its rooms are filled with rare and beautiful treasures."},
    {"reference": "Proverbs 1:7", "text": "The fear of the LORD is the beginning of knowledge, but fools despise wisdom and instruction."},
    {"reference": "Proverbs 11:14", "text": "For lack of guidance a nation falls, but victory is won through many advisers."},
    {"reference": "Psalm 119:105", "text": "Your word is a lamp for my feet, a light on my path."},
    {"reference": "Proverbs 12:15", "text": "The way of fools seems right to them, but the wise listen to advice."},
    {"reference": "Proverbs 18:15", "text": "The heart of the discerning acquires knowledge, for the ears of the wise seek it out."},
    {"reference": "Proverbs 13:16", "text": "All who are prudent act with knowledge, but fools expose their folly."},
    {"reference": "Proverbs 21:5", "text": "The plans of the diligent lead to profit as surely as haste leads to poverty."},
    {"reference": "Proverbs 22:3", "text": "The prudent see danger and take refuge, but the simple keep going and pay the penalty."},
    {"reference": "Isaiah 28:29", "text": "All this also comes from the LORD Almighty, whose plan is wonderful, whose wisdom is magnificent."},
    {"reference": "Proverbs 24:27", "text": "Put your outdoor work in order and get your fields ready; after that, build your house."},

    # === PEACE & COMFORT (15) ===
    {"reference": "Philippians 4:6-7", "text": "Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God. And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus."},
    {"reference": "John 14:27", "text": "Peace I leave with you; my peace I give you. I do not give to you as the world gives. Do not let your hearts be troubled and do not be afraid."},
    {"reference": "Psalm 23:4", "text": "Even though I walk through the darkest valley, I will fear no evil, for you are with me; your rod and your staff, they comfort me."},
    {"reference": "Matthew 11:28-30", "text": "Come to me, all you who are weary and burdened, and I will give you rest. Take my yoke upon you and learn from me, for I am gentle and humble in heart, and you will find rest for your souls."},
    {"reference": "Psalm 34:17-18", "text": "The righteous cry out, and the LORD hears them; he delivers them from all their troubles. The LORD is close to the brokenhearted and saves those who are crushed in spirit."},
    {"reference": "Isaiah 43:2", "text": "When you pass through the waters, I will be with you; and when you pass through the rivers, they will not sweep over you."},
    {"reference": "John 16:33", "text": "I have told you these things, so that in me you may have peace. In this world you will have trouble. But take heart! I have overcome the world."},
    {"reference": "Psalm 55:22", "text": "Cast your cares on the LORD and he will sustain you; he will never let the righteous be shaken."},
    {"reference": "1 Peter 5:7", "text": "Cast all your anxiety on him because he cares for you."},
    {"reference": "Psalm 94:19", "text": "When anxiety was great within me, your consolation brought me joy."},
    {"reference": "Romans 8:38-39", "text": "For I am convinced that neither death nor life, neither angels nor demons, neither the present nor the future, nor any powers, neither height nor depth, nor anything else in all creation, will be able to separate us from the love of God."},
    {"reference": "2 Corinthians 1:3-4", "text": "Praise be to the God and Father of our Lord Jesus Christ, the Father of compassion and the God of all comfort, who comforts us in all our troubles."},
    {"reference": "Isaiah 41:13", "text": "For I am the LORD your God who takes hold of your right hand and says to you, Do not fear; I will help you."},
    {"reference": "Psalm 4:8", "text": "In peace I will lie down and sleep, for you alone, LORD, make me dwell in safety."},
    {"reference": "Zephaniah 3:17", "text": "The LORD your God is with you, the Mighty Warrior who saves. He will take great delight in you; in his love he will no longer rebuke you, but will rejoice over you with singing."},

    # === PROSPERITY & PROVISION (15) ===
    {"reference": "Philippians 4:19", "text": "And my God will meet all your needs according to the riches of his glory in Christ Jesus."},
    {"reference": "Deuteronomy 8:18", "text": "But remember the LORD your God, for it is he who gives you the ability to produce wealth, and so confirms his covenant."},
    {"reference": "Psalm 1:3", "text": "That person is like a tree planted by streams of water, which yields its fruit in season and whose leaf does not wither — whatever they do prospers."},
    {"reference": "Malachi 3:10", "text": "Bring the whole tithe into the storehouse, that there may be food in my house. Test me in this, says the LORD Almighty, and see if I will not throw open the floodgates of heaven and pour out so much blessing that there will not be room enough to store it."},
    {"reference": "Proverbs 10:22", "text": "The blessing of the LORD brings wealth, without painful toil for it."},
    {"reference": "3 John 1:2", "text": "Dear friend, I pray that you may enjoy good health and that all may go well with you, even as your soul is getting along well."},
    {"reference": "Psalm 34:10", "text": "The lions may grow weak and hungry, but those who seek the LORD lack no good thing."},
    {"reference": "Luke 6:38", "text": "Give, and it will be given to you. A good measure, pressed down, shaken together and running over, will be poured into your lap."},
    {"reference": "Proverbs 13:11", "text": "Dishonest money dwindles away, but whoever gathers money little by little makes it grow."},
    {"reference": "Psalm 37:4", "text": "Take delight in the LORD, and he will give you the desires of your heart."},
    {"reference": "Psalm 23:1", "text": "The LORD is my shepherd, I lack nothing."},
    {"reference": "Matthew 6:33", "text": "But seek first his kingdom and his righteousness, and all these things will be given to you as well."},
    {"reference": "Proverbs 28:20", "text": "A faithful person will be richly blessed, but one eager to get rich will not go unpunished."},
    {"reference": "Ecclesiastes 5:19", "text": "Moreover, when God gives someone wealth and possessions, and the ability to enjoy them, to accept their lot and be happy in their toil — this is a gift of God."},
    {"reference": "2 Corinthians 9:8", "text": "And God is able to bless you abundantly, so that in all things at all times, having all that you need, you will abound in every good work."},

    # === JOY & GRATITUDE (10) ===
    {"reference": "Psalm 118:24", "text": "The LORD has done it this very day; let us rejoice today and be glad."},
    {"reference": "1 Thessalonians 5:16-18", "text": "Rejoice always, pray continually, give thanks in all circumstances; for this is God's will for you in Christ Jesus."},
    {"reference": "Psalm 16:11", "text": "You make known to me the path of life; you will fill me with joy in your presence, with eternal pleasures at your right hand."},
    {"reference": "James 1:17", "text": "Every good and perfect gift is from above, coming down from the Father of the heavenly lights, who does not change like shifting shadows."},
    {"reference": "Psalm 126:3", "text": "The LORD has done great things for us, and we are filled with joy."},
    {"reference": "Psalm 100:4", "text": "Enter his gates with thanksgiving and his courts with praise; give thanks to him and praise his name."},
    {"reference": "Philippians 4:4", "text": "Rejoice in the Lord always. I will say it again: Rejoice!"},
    {"reference": "Colossians 3:17", "text": "And whatever you do, whether in word or deed, do it all in the name of the Lord Jesus, giving thanks to God the Father through him."},
    {"reference": "Psalm 107:1", "text": "Give thanks to the LORD, for he is good; his love endures forever."},
    {"reference": "Romans 12:2", "text": "Do not conform to the pattern of this world, but be transformed by the renewing of your mind. Then you will be able to test and approve what God's will is — his good, pleasing and perfect will."},

    # === PROTECTION & SAFETY (10) ===
    {"reference": "Psalm 91:1-2", "text": "Whoever dwells in the shelter of the Most High will rest in the shadow of the Almighty. I will say of the LORD, 'He is my refuge and my fortress, my God, in whom I trust.'"},
    {"reference": "Proverbs 18:10", "text": "The name of the LORD is a fortified tower; the righteous run to it and are safe."},
    {"reference": "Psalm 121:7-8", "text": "The LORD will keep you from all harm — he will watch over your life; the LORD will watch over your coming and going both now and forevermore."},
    {"reference": "Psalm 34:7", "text": "The angel of the LORD encamps around those who fear him, and he delivers them."},
    {"reference": "2 Samuel 22:31", "text": "As for God, his way is perfect: The LORD's word is flawless; he shields all who take refuge in him."},
    {"reference": "Psalm 3:3", "text": "But you, LORD, are a shield around me, my glory, the One who lifts my head high."},
    {"reference": "Psalm 46:10", "text": "Be still, and know that I am God; I will be exalted among the nations, I will be exalted in the earth."},
    {"reference": "Isaiah 43:1", "text": "Do not fear, for I have redeemed you; I have summoned you by name; you are mine."},
    {"reference": "Psalm 32:7", "text": "You are my hiding place; you will protect me from trouble and surround me with songs of deliverance."},
    {"reference": "Deuteronomy 33:27", "text": "The eternal God is your refuge, and underneath are the everlasting arms."},

    # === PURPOSE & CALLING (10) ===
    {"reference": "Ephesians 2:10", "text": "For we are God's handiwork, created in Christ Jesus to do good works, which God prepared in advance for us to do."},
    {"reference": "Jeremiah 1:5", "text": "Before I formed you in the womb I knew you, before you were born I set you apart."},
    {"reference": "Philippians 1:6", "text": "Being confident of this, that he who began a good work in you will carry it on to completion until the day of Christ Jesus."},
    {"reference": "Romans 8:37", "text": "No, in all these things we are more than conquerors through him who loved us."},
    {"reference": "Isaiah 55:11", "text": "So is my word that goes out from my mouth: It will not return to me empty, but will accomplish what I desire and achieve the purpose for which I sent it."},
    {"reference": "Psalm 138:8", "text": "The LORD will vindicate me; your love, LORD, endures forever — do not abandon the works of your hands."},
    {"reference": "Proverbs 16:9", "text": "In their hearts humans plan their course, but the LORD establishes their steps."},
    {"reference": "Micah 6:8", "text": "He has shown you, O mortal, what is good. And what does the LORD require of you? To act justly and to love mercy and to walk humbly with your God."},
    {"reference": "Jeremiah 17:7-8", "text": "Blessed is the one who trusts in the LORD, whose confidence is in him. They will be like a tree planted by the water that sends out its roots by the stream."},
    {"reference": "Philippians 3:14", "text": "I press on toward the goal to win the prize for which God has called me heavenward in Christ Jesus."},

    # === DISCIPLINE & SELF-CONTROL (5) ===
    {"reference": "Proverbs 25:28", "text": "Like a city whose walls are broken through is a person who lacks self-control."},
    {"reference": "1 Corinthians 9:25", "text": "Everyone who competes in the games goes into strict training. They do it to get a crown that will not last, but we do it to get a crown that will last forever."},
    {"reference": "Proverbs 13:4", "text": "A sluggard's appetite is never filled, but the desires of the diligent are fully satisfied."},
    {"reference": "Galatians 5:22-23", "text": "But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness, gentleness and self-control. Against such things there is no law."},
    {"reference": "Titus 2:11-12", "text": "For the grace of God has appeared that offers salvation to all people. It teaches us to say 'No' to ungodliness and worldly passions, and to live self-controlled, upright and godly lives."},
]
